/** Auto-generated — do not edit. Run: npx tsx scripts/generate-dashboard-labels.ts */

export type DashboardLocale = "en" | "zh";

export const EN: Record<string, string> = {
  "common.imagePlayground": "Image Playground",
  "dashboard.apiKeys.active": "Active",
  "dashboard.apiKeys.apiKeyCreated": "API key created",
  "dashboard.apiKeys.apiKeyCreatedNamed": "API key created: {name}",
  "dashboard.apiKeys.apiKeyUnderstandingDesc": "Your credential to call Tokfai APIs — same rules as the API Key chapter in Docs.",
  "dashboard.apiKeys.apiKeyUnderstandingTitle": "What is a Tokfai API Key?",
  "dashboard.apiKeys.authHeaderHint": "Use this key in",
  "dashboard.apiKeys.buildPayload": "Build payload",
  "dashboard.apiKeys.buildStarterTemplate": "Build starter template",
  "dashboard.apiKeys.capacityRateLimitsLink": "Capacity & rate limits",
  "dashboard.apiKeys.cherryStudioGuide": "Cherry Studio guide",
  "dashboard.apiKeys.colActions": "Actions",
  "dashboard.apiKeys.colCreated": "Created",
  "dashboard.apiKeys.colLastUsed": "Last used",
  "dashboard.apiKeys.colName": "Name",
  "dashboard.apiKeys.colPrefix": "Prefix",
  "dashboard.apiKeys.colRevokedAt": "Revoked at",
  "dashboard.apiKeys.colStatus": "Status",
  "dashboard.apiKeys.commercialFaqGuide": "Commercial FAQ",
  "dashboard.apiKeys.copied": "Copied",
  "dashboard.apiKeys.copyAuthHeader": "Copy Authorization header",
  "dashboard.apiKeys.copyCherryConfig": "Copy Cherry config",
  "dashboard.apiKeys.copyCursorConfig": "Copy Cursor config",
  "dashboard.apiKeys.copyFullKey": "Copy full key",
  "dashboard.apiKeys.copying": "Copying...",
  "dashboard.apiKeys.copyKey": "Copy key",
  "dashboard.apiKeys.copyNodeSdkConfig": "Copy Node.js SDK config",
  "dashboard.apiKeys.copyOneLineChatCurl": "Copy one-line Chat curl",
  "dashboard.apiKeys.copyOneLineModelsCurl": "Copy one-line Models curl",
  "dashboard.apiKeys.copyPowerShellChatCurl": "Copy PowerShell Chat curl",
  "dashboard.apiKeys.copyPythonSdkConfig": "Copy Python SDK config",
  "dashboard.apiKeys.createApiKey": "Create API key",
  "dashboard.apiKeys.createApiKeyDesc": "Optional name for your reference. Leave blank to use the default name.",
  "dashboard.apiKeys.creating": "Creating...",
  "dashboard.apiKeys.cursorGuide": "Cursor guide",
  "dashboard.apiKeys.emptyCreateFirst": "Create your first API key",
  "dashboard.apiKeys.emptyRecharge": "Top up credits",
  "dashboard.apiKeys.emptyTitle": "No API keys yet. Create your first key to start testing — the full secret is shown once, so copy it immediately.",
  "dashboard.apiKeys.errorCode": "Code",
  "dashboard.apiKeys.errorHttpStatus": "HTTP status",
  "dashboard.apiKeys.errorRequestId": "request_id",
  "dashboard.apiKeys.goToCredits": "Go to Credits",
  "dashboard.apiKeys.goToUsage": "Go to Usage",
  "dashboard.apiKeys.integrationLinksTitle": "Try and verify",
  "dashboard.apiKeys.integrationWorkbench": "Integration workbench",
  "dashboard.apiKeys.keyName": "Key name",
  "dashboard.apiKeys.keyNamePlaceholder": "e.g. production",
  "dashboard.apiKeys.keyReadyMessage": "Your key is ready. Verify one request first, then plan capacity and hand off integration.",
  "dashboard.apiKeys.largeVolumeBatchGuide": "Large-volume Batch guide",
  "dashboard.apiKeys.largeVolumeIntegrationLink": "Large-volume integration",
  "dashboard.apiKeys.listUnavailableDesc": "The key list could not load — the API may be temporarily unavailable. You can still create a new key below, or retry after a few minutes.",
  "dashboard.apiKeys.listUnavailableTitle": "Could not load your API keys",
  "dashboard.apiKeys.loadError": "Could not load API keys",
  "dashboard.apiKeys.loadErrorAuthDesc": "Your session has expired. Please sign in again.",
  "dashboard.apiKeys.loadErrorTempDesc": "Unable to load API keys. Please try again later.",
  "dashboard.apiKeys.neverUsed": "Never used",
  "dashboard.apiKeys.nextStepBatch": "Batch API is in the Batch chapter in Docs.",
  "dashboard.apiKeys.nextStepCherry": "Cherry Studio setup is in the Cherry chapter in Docs.",
  "dashboard.apiKeys.nextStepCurl": "Copy one-line models curl to verify auth, or one-line chat curl for a full test (same as Docs API Key chapter).",
  "dashboard.apiKeys.nextStepCursor": "Cursor setup is in the Cursor chapter in Docs.",
  "dashboard.apiKeys.nextStepSdk": "See Docs for OpenAI SDK, Cursor, and Cherry Studio.",
  "dashboard.apiKeys.nextStepsTitle": "Connect via Tokfai API",
  "dashboard.apiKeys.oneTimeSecretDesc": "Copy and store this key now — it is shown only once at creation.",
  "dashboard.apiKeys.online500Guide": "500 online users guide",
  "dashboard.apiKeys.openStarterTemplates": "Open Starter Templates",
  "dashboard.apiKeys.pasteTerminalNote": "Paste and run in any terminal. No repo, no install, no cd.",
  "dashboard.apiKeys.productionHandoffTitle": "Production handoff",
  "dashboard.apiKeys.productionUseGuide": "Production use",
  "dashboard.apiKeys.quickStartDocs": "Quick start guide",
  "dashboard.apiKeys.retryBackoffGuide": "Retry & backoff guide",
  "dashboard.apiKeys.retryRateLimitGuide": "Retry & rate limit guide",
  "dashboard.apiKeys.revoke": "Revoke",
  "dashboard.apiKeys.revokeConfirm": "Revoke this API key? Existing apps using this key will stop working. This cannot be undone.",
  "dashboard.apiKeys.revoked": "Revoked",
  "dashboard.apiKeys.revoking": "Revoking...",
  "dashboard.apiKeys.savedMyKey": "I've saved my key",
  "dashboard.apiKeys.securityDesc": "Treat API keys like passwords. Never expose them in client-side code or public source code.",
  "dashboard.apiKeys.securityItem1": "Store keys on your server only — never embed them in mobile apps, browsers, or public frontends.",
  "dashboard.apiKeys.securityItem2": "If a key is leaked or exposed, revoke it immediately and create a replacement.",
  "dashboard.apiKeys.securityItem3": "The full secret is shown once at creation. After that, use Copy key on active keys to copy the full secret again.",
  "dashboard.apiKeys.securityItem4": "One API Key works for Chat, Image, and Batch — you do not need separate keys per model.",
  "dashboard.apiKeys.securityItem5": "If a key is leaked or exposed, Revoke it immediately and create a replacement.",
  "dashboard.apiKeys.securityTitle": "Keep your keys secure",
  "dashboard.apiKeys.sessionKeyDocsNote": "After you save your key, this browser session still fills Docs examples. Refreshing clears it — copy your key or one-line curl again if you see a placeholder.",
  "dashboard.apiKeys.startIntegration": "Start integration",
  "dashboard.apiKeys.startIntegrationWorkbench": "Start Integration Workbench",
  "dashboard.apiKeys.storeBackendSecurityNote": "Store your API Key on your backend. Do not expose it in browser frontend.",
  "dashboard.apiKeys.subtitleCreate": "Create keys to authenticate requests to {baseUrl}. The full secret is shown once when created. Active keys can be revealed and copied again with Copy key.",
  "dashboard.apiKeys.subtitleMeta": "View API key metadata for your Tokfai account.",
  "dashboard.apiKeys.title": "API Keys",
  "dashboard.apiKeys.verifyCredits": "Verify in Credits",
  "dashboard.apiKeys.verifyUsage": "Verify in Usage",
  "dashboard.apiKeys.viewApiDocs": "View API docs",
  "dashboard.apiKeys.viewApiKeyDocs": "API Key docs",
  "dashboard.apiKeys.viewDocs": "View docs",
  "dashboard.apiKeys.viewUsageCreditsDocs": "Usage & Credits guide",
  "dashboard.apiKeys.yourApiKey": "Your API key",
  "dashboard.apiKeys.yourApiKeys": "Your API keys",
  "dashboard.apiKeys.yourApiKeysDesc": "Prefixes are shown for identification. Use Copy key to copy the full secret for active keys.",
  "dashboard.imagePlayground.addImageUrl": "Add URL",
  "dashboard.imagePlayground.base64OnlyHint": "The API returned base64 image data (data[0].b64_json). Image Playground only previews URL responses — use the API directly or set response_format=url.",
  "dashboard.imagePlayground.copiedRequestId": "Copied",
  "dashboard.imagePlayground.copyApiRequest": "Copy API request",
  "dashboard.imagePlayground.copyRequestId": "Copy request ID",
  "dashboard.imagePlayground.createApiKey": "Create an API key",
  "dashboard.imagePlayground.createTestKey": "Create test key",
  "dashboard.imagePlayground.errors.billingNotChargedHint": "Failed requests are usually not charged. See Usage / Credits for the official record.",
  "dashboard.imagePlayground.errors.invalidDrop": "Drop PNG, JPG, or WEBP image files.",
  "dashboard.imagePlayground.errors.invalidToken": "API key is invalid or revoked. Create a new key.",
  "dashboard.imagePlayground.errors.keyNotRetrievable": "For security, full keys aren't stored long-term. Paste your key or create a new test key.",
  "dashboard.imagePlayground.errors.missingPrompt": "Please enter a prompt.",
  "dashboard.imagePlayground.errors.missingToken": "Missing API key. Create and paste an active key first.",
  "dashboard.imagePlayground.errors.pageImageNotFound": "Could not find a usable image on this page. Try another URL or upload the image directly.",
  "dashboard.imagePlayground.errors.tooManyImages": "Up to {max} input images are allowed.",
  "dashboard.imagePlayground.errors.unknown": "Request failed. Please try again later.",
  "dashboard.imagePlayground.estimatedCost": "Estimated cost: {credits} credits",
  "dashboard.imagePlayground.generate": "Generate",
  "dashboard.imagePlayground.generating": "Generating…",
  "dashboard.imagePlayground.imageToImage": "Image to Image",
  "dashboard.imagePlayground.inputImagesDesc": "Drag, upload, or paste URLs. Up to {max} images (PNG, JPG, WEBP). Leave empty for text-to-image.",
  "dashboard.imagePlayground.inputImagesDragHint": "PNG, JPG, WEBP · max 10 MB each",
  "dashboard.imagePlayground.inputImagesDragTitle": "Drag images here or click to upload",
  "dashboard.imagePlayground.inputImagesTitle": "Input images",
  "dashboard.imagePlayground.inputImagesUrlPlaceholder": "Image or page URL — Tokfai extracts the image when possible",
  "dashboard.imagePlayground.metaCreatedAt": "Created at",
  "dashboard.imagePlayground.metaModel": "Model",
  "dashboard.imagePlayground.modelComingSoon": "This model is coming soon and cannot be used in Playground yet.",
  "dashboard.imagePlayground.preparingImages": "Preparing input images…",
  "dashboard.imagePlayground.size": "Size",
  "dashboard.imagePlayground.successCreditsCharged": "Charged {credits} credits.",
  "dashboard.imagePlayground.successReconcileHint": "Copy request_id and search it in Usage and Credits to reconcile this generation.",
  "dashboard.imagePlayground.textToImage": "Text to Image",
  "dashboard.imagePlayground.title": "Image Playground",
  "dashboard.imagePlayground.toolbenchApiKeyLabel": "API Key",
  "dashboard.imagePlayground.toolbenchBalanceLabel": "Balance",
  "dashboard.imagePlayground.toolbenchBillingNoteShort": "Successful generations are charged. Failed calls are usually not charged.",
  "dashboard.imagePlayground.toolbenchCurrentKeyLine": "Current: {name} · {prefix}…",
  "dashboard.imagePlayground.toolbenchInputTitle": "Input",
  "dashboard.imagePlayground.toolbenchInsufficientCredits": "Insufficient credits — top up before generating.",
  "dashboard.imagePlayground.toolbenchManageKeysShort": "Manage",
  "dashboard.imagePlayground.toolbenchModelLabel": "Model",
  "dashboard.imagePlayground.toolbenchNoKey": "Create an API Key to call the Image API from your account.",
  "dashboard.imagePlayground.toolbenchOpenIntegrationDocs": "Open integration docs",
  "dashboard.imagePlayground.toolbenchPasteKeyShort": "Paste key",
  "dashboard.imagePlayground.toolbenchResultLoadingHint": "Keep this panel visible. The result will appear here.",
  "dashboard.imagePlayground.toolbenchResultLoadingTitle": "Generating…",
  "dashboard.imagePlayground.toolbenchResultPanelTitle": "Result",
  "dashboard.imagePlayground.toolbenchResultPlaceholder": "Generated image will appear here",
  "dashboard.imagePlayground.toolbenchRetry": "Retry",
  "dashboard.imagePlayground.toolbenchRunSettings": "Run settings",
  "dashboard.imagePlayground.toolbenchServiceDocs": "Service docs",
  "dashboard.imagePlayground.toolbenchSubtitle": "Prompt → optional reference images → Generate. Charged only on successful API responses.",
  "dashboard.imagePlayground.toolbenchViewImageApiDocs": "View Image API docs",
  "dashboard.imagePlayground.topUp": "Top up",
  "dashboard.imagePlayground.viewCredits": "View Credits",
  "dashboard.imagePlayground.viewImageApiDocs": "Image API docs",
  "dashboard.imagePlayground.viewUsage": "View Usage",
  "dashboard.imagePlayground.waitingForImages": "Waiting for input images to finish uploading or resolving…",
  "dashboard.models.buildPayloadAutoCheap": "Build payload — ecommerce batch",
  "dashboard.models.buildPayloadAutoFast": "Build payload — general/support chat",
  "dashboard.models.buildPayloadAutoPro": "Build payload — hospital/auto quality",
  "dashboard.models.buildPayloadImage": "Build payload — image",
  "dashboard.models.buildPayloadWithModel": "Build payload with this model",
  "dashboard.models.buildTemplateAutoCheap": "Build template — auto-cheap batch",
  "dashboard.models.buildTemplateAutoFast": "Build template — auto-fast chat",
  "dashboard.models.buildTemplateAutoPro": "Build template — auto-pro quality",
  "dashboard.models.buildTemplateImage": "Build template — gpt-image-2 image",
  "dashboard.models.buildTemplateWithModel": "Build template with this model",
  "dashboard.models.capacityPlannerLink": "Capacity planner",
  "dashboard.models.colApproxRmb": "Budget reference",
  "dashboard.models.colLongEstimate": "Long analysis / plan usage",
  "dashboard.models.colModelId": "Model ID",
  "dashboard.models.colPackageCredits": "Credits included",
  "dashboard.models.colPackagePlan": "Plan",
  "dashboard.models.colPackageUsageFit": "Typical fit",
  "dashboard.models.colShortEstimate": "Short chat / per image",
  "dashboard.models.colStatus": "Status",
  "dashboard.models.colType": "Type",
  "dashboard.models.copied": "Copied",
  "dashboard.models.copyCurlWithModel": "Copy one-line curl with this model",
  "dashboard.models.copyModelId": "Copy model id",
  "dashboard.models.exampleDesc": "For a real one-line curl with your key, copy from API Keys or Docs Quick Start. Example below uses a placeholder.",
  "dashboard.models.exampleTitle": "Minimal request",
  "dashboard.models.footerActions": "Next steps",
  "dashboard.models.footerApiKeys": "Create API key",
  "dashboard.models.footerCapacityGuide": "Capacity & rate limits",
  "dashboard.models.footerCredits": "Credits ledger",
  "dashboard.models.footerDocs": "View integration docs",
  "dashboard.models.footerHighTrafficBatch": "High traffic — Batch & capacity",
  "dashboard.models.footerIndustryTemplates": "Industry templates",
  "dashboard.models.footerPlayground": "Open Playground",
  "dashboard.models.footerProductionUse": "Production use",
  "dashboard.models.footerQuickStart": "Quick Start curl",
  "dashboard.models.footerRateLimits": "Rate limits",
  "dashboard.models.footerStartIntegration": "Start integration",
  "dashboard.models.footerUsage": "Check Usage",
  "dashboard.models.goLiveAutoCheapEcommerce": "Use auto-cheap for high-volume ecommerce copy",
  "dashboard.models.goLiveAutoFastFirst": "Use auto-fast for first test",
  "dashboard.models.goLiveAutoProQuality": "Use auto-pro for quality workloads",
  "dashboard.models.goLiveChooseModelPlan": "Choose model plan in capacity planner",
  "dashboard.models.goLiveOpenTracker": "Open go-live tracker",
  "dashboard.models.goLiveReadinessTitle": "Go-live readiness",
  "dashboard.models.highTrafficBatchGovernor": "High traffic: use Batch API and traffic governor with safe retry.",
  "dashboard.models.highTrafficBatchItems": "Batch: 500–1,000 items per job — async queue with polling.",
  "dashboard.models.highTrafficBatchNote": "High traffic? Use Batch API and the capacity guide for controlled concurrency.",
  "dashboard.models.highTrafficCapacityPlanner": "Use the capacity planner to pick concurrency, model, and Batch vs Chat split.",
  "dashboard.models.highTrafficChatConcurrency": "Chat: 25–50 controlled concurrent sync requests per app.",
  "dashboard.models.highTrafficClientQueue": "Use a client-side queue and concurrency governor; large jobs use Batch worker.",
  "dashboard.models.highTrafficImageConcurrency": "Image: 5–15 controlled concurrent requests (slow generation).",
  "dashboard.models.highTrafficIntegrationTitle": "High traffic integration",
  "dashboard.models.highTrafficNoInfiniteRetry": "Do not retry forever on 429 / 503 / 504 — cap attempts and use backoff.",
  "dashboard.models.highTrafficOnline500Note": "500 online does not mean 500 simultaneous upstream calls — use client-side queue limits.",
  "dashboard.models.highTrafficReconcile": "Reconcile every request_id in Usage and Credits (reference_id on ledger).",
  "dashboard.models.highTrafficUseBatch": "Use Batch API for large volume instead of sync Chat floods.",
  "dashboard.models.howToEstimateTitle": "How to estimate call cost?",
  "dashboard.models.inputPrice": "Input",
  "dashboard.models.listDisclaimer": "The model list is updated continuously.",
  "dashboard.models.openIntegrationWorkbench": "Open Integration Workbench",
  "dashboard.models.openUsageCreditsGuide": "Usage / Credits guide",
  "dashboard.models.outputPrice": "Output",
  "dashboard.models.overviewChat": "Chat models",
  "dashboard.models.overviewDefault": "Default model",
  "dashboard.models.overviewImage": "Image models",
  "dashboard.models.overviewTotal": "Available models",
  "dashboard.models.packageEstimateDesc": "Illustrative fit for {model} (chat) and {imageModel} (images). Not a usage guarantee.",
  "dashboard.models.packageEstimateRoughNote": "Rough guide only. Actual usable volume varies with model, prompt length, image size, and retries.",
  "dashboard.models.packageEstimateTitle": "Package usage reference",
  "dashboard.models.priceDisclaimer": "Budget reference: 1 yuan ≈ 1,000 credits (1 credit ≈ ¥0.001).",
  "dashboard.models.priceDisclaimerBudget": "Figures below are for budgeting only. Actual charges follow Usage and Credits ledger records.",
  "dashboard.models.priceDisclaimerTitle": "Price estimate disclaimer",
  "dashboard.models.productionGuidanceAutoCheap": "auto-cheap — low-cost batch-style workloads.",
  "dashboard.models.productionGuidanceAutoFast": "auto-fast — default recommendation for go-live smoke tests and general traffic.",
  "dashboard.models.productionGuidanceAutoPro": "auto-pro — higher-quality tasks when you need stronger reasoning.",
  "dashboard.models.productionGuidanceBatchNote": "Large volume jobs: prefer Batch API and reconcile each request_id in Usage / Credits.",
  "dashboard.models.productionGuidanceExplicit": "Explicit model IDs — for advanced customers who understand upstream trade-offs.",
  "dashboard.models.productionGuidanceTitle": "Production model strategy",
  "dashboard.models.recommendedStartingModel": "Recommended starting model: auto-fast",
  "dashboard.models.recommendedUseCase": "Best for",
  "dashboard.models.salesTip": "Start with a small package to complete integration testing. Confirm model, quality, and consumption before scaling volume.",
  "dashboard.models.scaleSafelyTitle": "Scale safely",
  "dashboard.models.smartRoutingDesc": "Use auto-* aliases for a stable entry point. Tokfai tries upstream models in order and returns the model that actually succeeded.",
  "dashboard.models.smartRoutingRealModelNote": "You can still pass a real model ID (e.g. gpt-5.4). Tokfai will not auto-fallback for explicit IDs — you get upstream_model_busy if that model is hot.",
  "dashboard.models.smartRoutingTitle": "Alias / Smart routing",
  "dashboard.models.starterTemplateAutoCheap": "auto-cheap → Ecommerce batch starter",
  "dashboard.models.starterTemplateAutoFast": "auto-fast → Chat starter template",
  "dashboard.models.starterTemplateAutoPro": "auto-pro → Quality Chat starter",
  "dashboard.models.starterTemplateHint": "Use this model in a starter template:",
  "dashboard.models.starterTemplateImage": "gpt-image-2 → Image starter template",
  "dashboard.models.startFromModelAutoCheap": "auto-cheap — high-volume ecommerce copy",
  "dashboard.models.startFromModelAutoFast": "auto-fast — first test",
  "dashboard.models.startFromModelAutoPro": "auto-pro — quality workloads",
  "dashboard.models.startFromModelTitle": "Start integration from this model",
  "dashboard.models.statusAvailable": "Available",
  "dashboard.models.statusComingSoon": "Coming soon",
  "dashboard.models.statusPaused": "Paused",
  "dashboard.models.subtitle": "Browse available Tokfai models, capabilities, recommended use cases, and billing notes.",
  "dashboard.models.tableDesc": "Model IDs for API requests and Playgrounds.",
  "dashboard.models.tableTitle": "Model list",
  "dashboard.models.title": "Models",
  "dashboard.models.usageTipsTitle": "Usage tips",
  "dashboard.models.verificationUnavailableNote": "If live verification is temporarily unavailable, choose your model plan now and verify later from Integration Workbench.",
  "dashboard.models.viewCreditsLedger": "View Credits ledger",
  "dashboard.playground.apiKey": "API key",
  "dashboard.playground.apiKeyLoadTimedOut": "Timed out loading the selected API key. Paste the full secret or try again.",
  "dashboard.playground.copied": "Copied",
  "dashboard.playground.copyRequestId": "Copy request_id",
  "dashboard.playground.copySecret": "Copy secret",
  "dashboard.playground.costHint": "Playground calls consume credits. Check your balance first. Actual charges are recorded in the credits ledger.",
  "dashboard.playground.createdAt": "created_at",
  "dashboard.playground.createTestKey": "Create test key",
  "dashboard.playground.creatingTestKey": "Creating…",
  "dashboard.playground.creditsCharged": "credits charged",
  "dashboard.playground.currentKeySelection": "Current selection: {name} ({prefix}…)",
  "dashboard.playground.errors.invalidToken": "API key is invalid or revoked. Create a new key.",
  "dashboard.playground.errors.keyNotRetrievable": "For security, full keys aren't stored long-term. Paste your key or create a new test key.",
  "dashboard.playground.errors.missingPrompt": "Please enter a prompt.",
  "dashboard.playground.errors.missingToken": "Missing API key. Create and paste an active key first.",
  "dashboard.playground.errors.unknown": "Request failed. Please try again later.",
  "dashboard.playground.errors.upstreamError": "The selected model is temporarily unavailable or under high load.",
  "dashboard.playground.forImageModels": "For image models, use",
  "dashboard.playground.fullApiKey": "Full API key",
  "dashboard.playground.goToApiKeys": "Go to API Keys",
  "dashboard.playground.hideKey": "Hide",
  "dashboard.playground.inputTokens": "input tokens",
  "dashboard.playground.manageApiKeys": "Manage API Keys",
  "dashboard.playground.manageApiKeysHint": "To revoke or delete keys, go to the API Keys page.",
  "dashboard.playground.model": "Model",
  "dashboard.playground.noKeyBody": "Create a test key to run your first real Playground call.",
  "dashboard.playground.noKeyTitle": "No active API Key yet",
  "dashboard.playground.outputTokens": "output tokens",
  "dashboard.playground.pasteKey": "Paste key",
  "dashboard.playground.pasteKeySecurityHint": "The key is kept in this page only and is not saved. Do not use on shared devices.",
  "dashboard.playground.pasteOtherKey": "Paste another key",
  "dashboard.playground.productionKeyHint": "For production, create and copy your sk-tokfai key on the API Keys page.",
  "dashboard.playground.prompt": "Prompt",
  "dashboard.playground.promptPlaceholder": "Enter test content, e.g. introduce Tokfai API in one sentence.",
  "dashboard.playground.request": "Test request",
  "dashboard.playground.requestDesc": "Select or create an API key, pick a chat model, and send one non-streaming message.",
  "dashboard.playground.requestedModel": "Requested model",
  "dashboard.playground.requestId": "request_id",
  "dashboard.playground.requestStatus": "Status",
  "dashboard.playground.resolvedModel": "Resolved model",
  "dashboard.playground.responseContent": "Response",
  "dashboard.playground.responsePlaceholder": "The model response will appear here after you send.",
  "dashboard.playground.resultTitle": "Result",
  "dashboard.playground.run": "Send test",
  "dashboard.playground.running": "Sending…",
  "dashboard.playground.secretNotStored": "The full secret is loaded only for this request and is not stored in the browser.",
  "dashboard.playground.secretOnceHint": "Full secret is shown only once at creation. After refresh it cannot be viewed again — create a new key if lost.",
  "dashboard.playground.selectKey": "Select key",
  "dashboard.playground.showKey": "Show",
  "dashboard.playground.statusFailed": "Failed",
  "dashboard.playground.statusSuccess": "Success",
  "dashboard.playground.subtitle": "Choose a model, send a test request, and verify the Tokfai API works.",
  "dashboard.playground.successBalanceHint": "Recorded in",
  "dashboard.playground.successReconcileHint": "Copy request_id and search it in Usage and Credits to reconcile this call.",
  "dashboard.playground.testKeyCreated": "Test key created. Copy the full secret — it won't be shown again after refresh.",
  "dashboard.playground.testNow": "Test now",
  "dashboard.playground.title": "Playground",
  "dashboard.playground.tokensNotReturned": "—",
  "dashboard.playground.totalTokens": "total tokens",
  "dashboard.playground.usageFallback": "Usage for this call is recorded in the credits ledger at /dashboard/credits.",
  "dashboard.playground.viewChatApiDocs": "Chat API docs",
  "dashboard.playground.viewCredits": "View Credits",
  "dashboard.playground.viewCreditsLedger": "View credits ledger",
  "dashboard.playground.viewDocs": "View docs",
  "dashboard.playground.viewModels": "View models",
  "dashboard.playground.viewOpenAiSdkDocs": "OpenAI SDK docs",
  "dashboard.playground.viewUsage": "View Usage",
  "dashboard.playground.waitingForModel": "Waiting for the model…",
  "dashboard.shell.lowCredits": "Low credits",
  "dashboard.usage.copiedRequestId": "Copied",
  "dashboard.usage.copyRequestId": "Copy request ID",
  "dashboard.usage.loadingRecentRequests": "Recent requests",
  "dashboard.usage.loadingRecentRequestsDesc": "Loading the latest usage logs.",
  "integration.apiKeyBulletAuthHeader": "Header format is always Authorization: Bearer sk-tokfai_xxx (replace xxx with your secret).",
  "integration.apiKeyBulletOneKeyAllApis": "One API Key works for Chat API, Image API, and Batch API — you do not need a separate key per model.",
  "integration.apiKeyBulletOneTime": "The full secret is shown once when you create a key — copy it immediately.",
  "integration.apiKeyBulletReveal": "Active keys can be copied again from API Keys via Copy key (reveal).",
  "integration.apiKeyBulletRevoke": "If a key is leaked, Revoke it immediately and create a new key.",
  "integration.apiKeyBulletServerSide": "Store keys on servers, scripts, IDE, or gateway configs only — never in public frontends or public source code.",
  "integration.apiKeyCopyNowTitle": "You can copy now",
  "integration.apiReadiness.apiKeysHint": "If live verification is unavailable, keep this key safe and continue with the Integration Workbench.",
  "integration.nav500OnlineReadiness": "500 online readiness",
  "integration.navCapacityPlanner": "Capacity planner",
  "integration.navRetryBackoff": "Retry & backoff",
  "integration.navTrafficGovernor": "Traffic governor",
  "integration.oneLineCurlPasteAnywhere": "Paste in any terminal. No install. No project folder required.",
  "integration.starterTemplates.openLibrary": "Open Starter Templates",
  "integration.trafficGovernor.scaleSafelyTitle": "Scale safely",
  "integration.troubleshooting.curlFailsTitle": "If the curl fails",
  "integration.troubleshooting.invalidTokenGuide": "invalid_token guide",
  "integration.troubleshooting.missingTokenGuide": "missing_token guide",
  "integration.troubleshooting.openTroubleshooting": "Open troubleshooting",
  "quickstart.copied": "Copied",
  "quickstart.copy": "Copy",
};

export const ZH: Record<string, string> = {
  "common.imagePlayground": "Image Playground",
  "dashboard.apiKeys.active": "活跃",
  "dashboard.apiKeys.apiKeyCreated": "API 密钥已创建",
  "dashboard.apiKeys.apiKeyCreatedNamed": "API 密钥已创建：{name}",
  "dashboard.apiKeys.apiKeyUnderstandingDesc": "调用 Tokfai API 的凭证——规则与文档 API Key 章节一致。",
  "dashboard.apiKeys.apiKeyUnderstandingTitle": "什么是 Tokfai API Key？",
  "dashboard.apiKeys.authHeaderHint": "在请求中使用",
  "dashboard.apiKeys.buildPayload": "生成 payload",
  "dashboard.apiKeys.buildStarterTemplate": "生成接入模板",
  "dashboard.apiKeys.capacityRateLimitsLink": "容量与限流",
  "dashboard.apiKeys.cherryStudioGuide": "Cherry Studio 接入指南",
  "dashboard.apiKeys.colActions": "操作",
  "dashboard.apiKeys.colCreated": "创建时间",
  "dashboard.apiKeys.colLastUsed": "最近使用",
  "dashboard.apiKeys.colName": "名称",
  "dashboard.apiKeys.colPrefix": "Prefix",
  "dashboard.apiKeys.colRevokedAt": "撤销时间",
  "dashboard.apiKeys.colStatus": "状态",
  "dashboard.apiKeys.commercialFaqGuide": "商业 FAQ",
  "dashboard.apiKeys.copied": "已复制",
  "dashboard.apiKeys.copyAuthHeader": "复制 Authorization header",
  "dashboard.apiKeys.copyCherryConfig": "复制 Cherry 配置",
  "dashboard.apiKeys.copyCursorConfig": "复制 Cursor 配置",
  "dashboard.apiKeys.copyFullKey": "复制完整密钥",
  "dashboard.apiKeys.copying": "复制中…",
  "dashboard.apiKeys.copyKey": "复制密钥",
  "dashboard.apiKeys.copyNodeSdkConfig": "复制 Node.js SDK 配置",
  "dashboard.apiKeys.copyOneLineChatCurl": "复制单行 Chat curl",
  "dashboard.apiKeys.copyOneLineModelsCurl": "复制单行 Models curl",
  "dashboard.apiKeys.copyPowerShellChatCurl": "复制 PowerShell Chat curl",
  "dashboard.apiKeys.copyPythonSdkConfig": "复制 Python SDK 配置",
  "dashboard.apiKeys.createApiKey": "创建 API 密钥",
  "dashboard.apiKeys.createApiKeyDesc": "可选名称，便于区分。留空则使用默认名称。",
  "dashboard.apiKeys.creating": "创建中…",
  "dashboard.apiKeys.cursorGuide": "Cursor 接入指南",
  "dashboard.apiKeys.emptyCreateFirst": "创建第一个 API Key",
  "dashboard.apiKeys.emptyRecharge": "去充值积分",
  "dashboard.apiKeys.emptyTitle": "还没有 API 密钥。创建第一把密钥即可开始测试——完整 secret 仅展示一次，请立即复制。",
  "dashboard.apiKeys.errorCode": "错误码",
  "dashboard.apiKeys.errorHttpStatus": "HTTP 状态",
  "dashboard.apiKeys.errorRequestId": "request_id",
  "dashboard.apiKeys.goToCredits": "前往 Credits",
  "dashboard.apiKeys.goToUsage": "前往 Usage",
  "dashboard.apiKeys.integrationLinksTitle": "体验与核对",
  "dashboard.apiKeys.integrationWorkbench": "接入工作台",
  "dashboard.apiKeys.keyName": "密钥名称",
  "dashboard.apiKeys.keyNamePlaceholder": "例如 production",
  "dashboard.apiKeys.keyReadyMessage": "密钥已就绪。请先验证一次请求，再规划容量并完成接入交接。",
  "dashboard.apiKeys.largeVolumeBatchGuide": "大批量 Batch 指南",
  "dashboard.apiKeys.largeVolumeIntegrationLink": "大批量接入",
  "dashboard.apiKeys.listUnavailableDesc": "密钥列表无法加载 — API 可能暂时不可用。你仍可在下方创建新密钥，或几分钟后重试。",
  "dashboard.apiKeys.listUnavailableTitle": "无法加载 API 密钥列表",
  "dashboard.apiKeys.loadError": "无法加载 API 密钥",
  "dashboard.apiKeys.loadErrorAuthDesc": "登录状态异常，请重新登录。",
  "dashboard.apiKeys.loadErrorTempDesc": "无法加载 API 密钥，请稍后重试。",
  "dashboard.apiKeys.neverUsed": "从未使用",
  "dashboard.apiKeys.nextStepBatch": "Batch API 见文档 Batch 章节。",
  "dashboard.apiKeys.nextStepCherry": "Cherry Studio 配置见文档 Cherry 章节。",
  "dashboard.apiKeys.nextStepCurl": "复制单行 models curl 验证鉴权，或单行 chat curl 做完整测试（与文档 API Key 章节一致）。",
  "dashboard.apiKeys.nextStepCursor": "Cursor 配置见文档 Cursor 章节。",
  "dashboard.apiKeys.nextStepSdk": "更多接入方式见文档：OpenAI SDK、Cursor、Cherry Studio。",
  "dashboard.apiKeys.nextStepsTitle": "通过 Tokfai API 接入",
  "dashboard.apiKeys.oneTimeSecretDesc": "请立即复制并妥善保存——完整密钥仅在创建时展示一次。",
  "dashboard.apiKeys.online500Guide": "500 人在线指南",
  "dashboard.apiKeys.openStarterTemplates": "打开接入模板库",
  "dashboard.apiKeys.pasteTerminalNote": "在任意终端粘贴运行。无需仓库、无需安装、无需 cd。",
  "dashboard.apiKeys.productionHandoffTitle": "生产交付",
  "dashboard.apiKeys.productionUseGuide": "生产上线",
  "dashboard.apiKeys.quickStartDocs": "快速上手指南",
  "dashboard.apiKeys.retryBackoffGuide": "重试与退避指南",
  "dashboard.apiKeys.retryRateLimitGuide": "重试与限流指南",
  "dashboard.apiKeys.revoke": "吊销",
  "dashboard.apiKeys.revokeConfirm": "确定吊销此 API 密钥？使用该密钥的应用将无法继续工作，且无法恢复。",
  "dashboard.apiKeys.revoked": "已吊销",
  "dashboard.apiKeys.revoking": "吊销中…",
  "dashboard.apiKeys.savedMyKey": "我已保存密钥",
  "dashboard.apiKeys.securityDesc": "请将 API Key 视为密码，不要暴露在客户端代码或公开源码中。",
  "dashboard.apiKeys.securityItem1": "API Key 只应保存在服务端——不要写入移动应用、浏览器或公开前端。",
  "dashboard.apiKeys.securityItem2": "若密钥泄露或误提交到 git，请立即 Revoke 并创建新密钥。",
  "dashboard.apiKeys.securityItem3": "完整 secret 仅在创建时完整展示；之后可通过活跃密钥的「复制密钥」再次复制完整 secret。",
  "dashboard.apiKeys.securityItem4": "一把 API Key 可用于 Chat、Image、Batch——无需为每个模型单独创建密钥。",
  "dashboard.apiKeys.securityItem5": "若密钥泄露或误提交，请立即 Revoke 并创建新密钥。",
  "dashboard.apiKeys.securityTitle": "保护你的密钥",
  "dashboard.apiKeys.sessionKeyDocsNote": "点击「我已保存密钥」后，本浏览器会话仍会自动填充 Docs 示例。刷新页面会清空 — 若出现占位符请重新复制密钥或单行 curl。",
  "dashboard.apiKeys.startIntegration": "开始接入",
  "dashboard.apiKeys.startIntegrationWorkbench": "打开接入工作台",
  "dashboard.apiKeys.storeBackendSecurityNote": "请将 API Key 保存在后端。禁止在浏览器前端暴露。",
  "dashboard.apiKeys.subtitleCreate": "创建密钥以向 {baseUrl} 发起认证请求。完整密钥仅在创建时展示一次；活跃密钥可通过「复制密钥」再次获取。",
  "dashboard.apiKeys.subtitleMeta": "查看 Tokfai 账户的 API 密钥元数据。",
  "dashboard.apiKeys.title": "API 密钥",
  "dashboard.apiKeys.verifyCredits": "在 Credits 核对",
  "dashboard.apiKeys.verifyUsage": "在 Usage 核对",
  "dashboard.apiKeys.viewApiDocs": "查看 API 文档",
  "dashboard.apiKeys.viewApiKeyDocs": "API Key 文档",
  "dashboard.apiKeys.viewDocs": "查看文档",
  "dashboard.apiKeys.viewUsageCreditsDocs": "Usage / Credits 指南",
  "dashboard.apiKeys.yourApiKey": "你的 API 密钥",
  "dashboard.apiKeys.yourApiKeys": "你的 API 密钥",
  "dashboard.apiKeys.yourApiKeysDesc": "列表展示 prefix 便于识别。活跃密钥可通过「复制密钥」获取完整 secret。",
  "dashboard.imagePlayground.addImageUrl": "添加 URL",
  "dashboard.imagePlayground.base64OnlyHint": "API 返回了 base64 图像数据（data[0].b64_json）。Image Playground 仅预览 URL 响应 — 请直接调用 API 或设置 response_format=url。",
  "dashboard.imagePlayground.copiedRequestId": "已复制",
  "dashboard.imagePlayground.copyApiRequest": "复制 API 请求",
  "dashboard.imagePlayground.copyRequestId": "复制 request_id",
  "dashboard.imagePlayground.createApiKey": "创建 API 密钥",
  "dashboard.imagePlayground.createTestKey": "创建测试 Key",
  "dashboard.imagePlayground.errors.billingNotChargedHint": "失败请求通常不会扣费，以 Usage / Credits 记录为准。",
  "dashboard.imagePlayground.errors.invalidDrop": "请拖入 PNG、JPG 或 WEBP 图片文件。",
  "dashboard.imagePlayground.errors.invalidToken": "API Key 无效或已吊销，请重新创建。",
  "dashboard.imagePlayground.errors.keyNotRetrievable": "出于安全考虑，完整 key 不会长期保存。请粘贴 key，或重新创建一个测试 Key。",
  "dashboard.imagePlayground.errors.missingPrompt": "请输入 prompt。",
  "dashboard.imagePlayground.errors.missingToken": "缺少 API Key，请先创建并选择可用密钥。",
  "dashboard.imagePlayground.errors.pageImageNotFound": "无法从该页面解析可用图片。请换用其他 URL 或直接上传图片。",
  "dashboard.imagePlayground.errors.tooManyImages": "最多允许 {max} 张输入图。",
  "dashboard.imagePlayground.errors.unknown": "请求失败，请稍后重试。",
  "dashboard.imagePlayground.estimatedCost": "预计消耗：{credits} credits",
  "dashboard.imagePlayground.generate": "生成",
  "dashboard.imagePlayground.generating": "生成中…",
  "dashboard.imagePlayground.imageToImage": "图生图",
  "dashboard.imagePlayground.inputImagesDesc": "拖拽、上传或粘贴 URL。最多 {max} 张（PNG、JPG、WEBP）。留空则为文生图。",
  "dashboard.imagePlayground.inputImagesDragHint": "PNG、JPG、WEBP · 单张最大 10 MB",
  "dashboard.imagePlayground.inputImagesDragTitle": "拖拽图片到此处或点击上传",
  "dashboard.imagePlayground.inputImagesTitle": "输入图片",
  "dashboard.imagePlayground.inputImagesUrlPlaceholder": "图片或网页 URL——Tokfai 会尝试自动提取图片",
  "dashboard.imagePlayground.metaCreatedAt": "创建时间",
  "dashboard.imagePlayground.metaModel": "模型",
  "dashboard.imagePlayground.modelComingSoon": "该模型即将上线，暂不能在 Playground 中使用。",
  "dashboard.imagePlayground.preparingImages": "准备输入图…",
  "dashboard.imagePlayground.size": "尺寸",
  "dashboard.imagePlayground.successCreditsCharged": "本次扣费 {credits} credits。",
  "dashboard.imagePlayground.successReconcileHint": "复制 request_id，在 Usage 与 Credits 中搜索以核对本次生成。",
  "dashboard.imagePlayground.textToImage": "文生图",
  "dashboard.imagePlayground.title": "Image Playground",
  "dashboard.imagePlayground.toolbenchApiKeyLabel": "API Key",
  "dashboard.imagePlayground.toolbenchBalanceLabel": "余额",
  "dashboard.imagePlayground.toolbenchBillingNoteShort": "成功生成会扣费，失败通常不扣费。",
  "dashboard.imagePlayground.toolbenchCurrentKeyLine": "当前：{name} · {prefix}…",
  "dashboard.imagePlayground.toolbenchInputTitle": "输入",
  "dashboard.imagePlayground.toolbenchInsufficientCredits": "余额不足——请先充值再生成。",
  "dashboard.imagePlayground.toolbenchManageKeysShort": "管理",
  "dashboard.imagePlayground.toolbenchModelLabel": "模型",
  "dashboard.imagePlayground.toolbenchNoKey": "创建 API Key 后即可从你的账户调用 Image API。",
  "dashboard.imagePlayground.toolbenchOpenIntegrationDocs": "打开接入文档",
  "dashboard.imagePlayground.toolbenchPasteKeyShort": "粘贴密钥",
  "dashboard.imagePlayground.toolbenchResultLoadingHint": "请保持此面板可见，结果将显示在这里。",
  "dashboard.imagePlayground.toolbenchResultLoadingTitle": "生成中…",
  "dashboard.imagePlayground.toolbenchResultPanelTitle": "结果",
  "dashboard.imagePlayground.toolbenchResultPlaceholder": "生成的图片将显示在这里",
  "dashboard.imagePlayground.toolbenchRetry": "重试",
  "dashboard.imagePlayground.toolbenchRunSettings": "调用设置",
  "dashboard.imagePlayground.toolbenchServiceDocs": "服务文档",
  "dashboard.imagePlayground.toolbenchSubtitle": "输入 Prompt → 可选参考图 → 生成。仅成功响应才扣费。",
  "dashboard.imagePlayground.toolbenchViewImageApiDocs": "查看 Image API 文档",
  "dashboard.imagePlayground.topUp": "去充值",
  "dashboard.imagePlayground.viewCredits": "查看 Credits",
  "dashboard.imagePlayground.viewImageApiDocs": "Image API 文档",
  "dashboard.imagePlayground.viewUsage": "查看 Usage",
  "dashboard.imagePlayground.waitingForImages": "等待输入图上传或解析完成…",
  "dashboard.models.buildPayloadAutoCheap": "生成 payload — 电商 Batch",
  "dashboard.models.buildPayloadAutoFast": "生成 payload — 通用/客服 Chat",
  "dashboard.models.buildPayloadAutoPro": "生成 payload — 医院/车企质量",
  "dashboard.models.buildPayloadImage": "生成 payload — 图像",
  "dashboard.models.buildPayloadWithModel": "用此 model 生成 payload",
  "dashboard.models.buildTemplateAutoCheap": "生成模板 — auto-cheap Batch",
  "dashboard.models.buildTemplateAutoFast": "生成模板 — auto-fast Chat",
  "dashboard.models.buildTemplateAutoPro": "生成模板 — auto-pro 质量",
  "dashboard.models.buildTemplateImage": "生成模板 — gpt-image-2 图像",
  "dashboard.models.buildTemplateWithModel": "用此 model 生成模板",
  "dashboard.models.capacityPlannerLink": "容量规划器",
  "dashboard.models.colApproxRmb": "预算参考",
  "dashboard.models.colLongEstimate": "长分析 / 套餐可用量",
  "dashboard.models.colModelId": "模型 ID",
  "dashboard.models.colPackageCredits": "到账 credits",
  "dashboard.models.colPackagePlan": "套餐",
  "dashboard.models.colPackageUsageFit": "适用参考",
  "dashboard.models.colShortEstimate": "短对话 / 每张",
  "dashboard.models.colStatus": "状态",
  "dashboard.models.colType": "类型",
  "dashboard.models.copied": "已复制",
  "dashboard.models.copyCurlWithModel": "复制此模型单行 curl",
  "dashboard.models.copyModelId": "复制 model id",
  "dashboard.models.exampleDesc": "带真实密钥的单行 curl 请从 API Keys 或 Docs Quick Start 复制。下方示例使用占位符。",
  "dashboard.models.exampleTitle": "最小请求示例",
  "dashboard.models.footerActions": "下一步",
  "dashboard.models.footerApiKeys": "创建 API Key",
  "dashboard.models.footerCapacityGuide": "容量与限流",
  "dashboard.models.footerCredits": "查看积分账本",
  "dashboard.models.footerDocs": "查看接入文档",
  "dashboard.models.footerHighTrafficBatch": "高流量 — Batch 与容量",
  "dashboard.models.footerIndustryTemplates": "行业模板",
  "dashboard.models.footerPlayground": "打开 Playground",
  "dashboard.models.footerProductionUse": "生产上线",
  "dashboard.models.footerQuickStart": "Quick Start curl",
  "dashboard.models.footerRateLimits": "限流与大批量",
  "dashboard.models.footerStartIntegration": "开始接入",
  "dashboard.models.footerUsage": "查看 Usage",
  "dashboard.models.goLiveAutoCheapEcommerce": "电商大批量文案使用 auto-cheap",
  "dashboard.models.goLiveAutoFastFirst": "首次测试使用 auto-fast",
  "dashboard.models.goLiveAutoProQuality": "高质量任务使用 auto-pro",
  "dashboard.models.goLiveChooseModelPlan": "在容量规划器中选择模型方案",
  "dashboard.models.goLiveOpenTracker": "打开上线跟踪器",
  "dashboard.models.goLiveReadinessTitle": "上线就绪",
  "dashboard.models.highTrafficBatchGovernor": "高流量：使用 Batch API、流量治理与安全重试。",
  "dashboard.models.highTrafficBatchItems": "Batch：单任务 500–1,000 条 — 异步队列轮询。",
  "dashboard.models.highTrafficBatchNote": "高流量？请用 Batch API 并阅读容量指南以控制并发。",
  "dashboard.models.highTrafficCapacityPlanner": "用容量规划器选择并发、模型与 Batch / Chat 分流。",
  "dashboard.models.highTrafficChatConcurrency": "Chat：每应用 25–50 路受控同步并发。",
  "dashboard.models.highTrafficClientQueue": "使用客户端队列与并发治理；大批量任务走 Batch worker。",
  "dashboard.models.highTrafficImageConcurrency": "Image：5–15 路受控并发（慢速生成）。",
  "dashboard.models.highTrafficIntegrationTitle": "高流量接入",
  "dashboard.models.highTrafficNoInfiniteRetry": "429 / 503 / 504 禁止无限重试 — 限制次数并退避。",
  "dashboard.models.highTrafficOnline500Note": "500 online 不等于 500 路同时打上游 — 请用客户端队列限流。",
  "dashboard.models.highTrafficReconcile": "在 Usage / Credits 用 request_id 对账（账本 reference_id）。",
  "dashboard.models.highTrafficUseBatch": "大批量请用 Batch API，勿用同步 Chat 洪峰。",
  "dashboard.models.howToEstimateTitle": "如何估算调用成本？",
  "dashboard.models.inputPrice": "Input",
  "dashboard.models.listDisclaimer": "模型列表会持续更新。",
  "dashboard.models.openIntegrationWorkbench": "打开接入工作台",
  "dashboard.models.openUsageCreditsGuide": "Usage / Credits 指南",
  "dashboard.models.outputPrice": "Output",
  "dashboard.models.overviewChat": "对话模型",
  "dashboard.models.overviewDefault": "推荐默认模型",
  "dashboard.models.overviewImage": "图像模型",
  "dashboard.models.overviewTotal": "可用模型数",
  "dashboard.models.packageEstimateDesc": "对话参考模型 {model}，图像参考 {imageModel}。以下为适用场景说明，非用量承诺。",
  "dashboard.models.packageEstimateRoughNote": "以下为粗略估算，实际可用量会随模型、输入长度、图片尺寸、重试次数变化。",
  "dashboard.models.packageEstimateTitle": "套餐适用参考",
  "dashboard.models.priceDisclaimer": "预算参考口径：1 元≈1000 credits（1 credit≈¥0.001）。",
  "dashboard.models.priceDisclaimerBudget": "以下仅为预算参考，实际扣费以 Usage / Credits 账本为准。",
  "dashboard.models.priceDisclaimerTitle": "价格估算说明",
  "dashboard.models.productionGuidanceAutoCheap": "auto-cheap — 批量低成本任务。",
  "dashboard.models.productionGuidanceAutoFast": "auto-fast — 默认推荐，适合上线冒烟与普通业务。",
  "dashboard.models.productionGuidanceAutoPro": "auto-pro — 高质量任务。",
  "dashboard.models.productionGuidanceBatchNote": "大批量调用建议结合 Batch API，并在 Usage / Credits 按 request_id 对账。",
  "dashboard.models.productionGuidanceExplicit": "真实模型 ID — 高级客户按需选择。",
  "dashboard.models.productionGuidanceTitle": "生产模型策略",
  "dashboard.models.recommendedStartingModel": "推荐起步模型：auto-fast",
  "dashboard.models.recommendedUseCase": "适合场景",
  "dashboard.models.salesTip": "建议先用小套餐完成接入测试，确认模型、质量和消耗后再放量。",
  "dashboard.models.scaleSafelyTitle": "安全扩容",
  "dashboard.models.smartRoutingDesc": "使用 auto-* 别名作为稳定入口。Tokfai 按顺序尝试上游模型，并在响应中返回实际成功的 model。",
  "dashboard.models.smartRoutingRealModelNote": "仍可传入真实 model ID（如 gpt-5.4）。明确指定时 Tokfai 不会自动 fallback — 若该模型繁忙将返回 upstream_model_busy。",
  "dashboard.models.smartRoutingTitle": "别名 / 智能路由",
  "dashboard.models.starterTemplateAutoCheap": "auto-cheap → 电商 Batch 模板",
  "dashboard.models.starterTemplateAutoFast": "auto-fast → Chat 起步模板",
  "dashboard.models.starterTemplateAutoPro": "auto-pro → 高质量 Chat 模板",
  "dashboard.models.starterTemplateHint": "在接入模板库中使用此模型：",
  "dashboard.models.starterTemplateImage": "gpt-image-2 → Image 起步模板",
  "dashboard.models.startFromModelAutoCheap": "auto-cheap — 电商大批量文案",
  "dashboard.models.startFromModelAutoFast": "auto-fast — 首次测试",
  "dashboard.models.startFromModelAutoPro": "auto-pro — 高质量任务",
  "dashboard.models.startFromModelTitle": "从此模型开始接入",
  "dashboard.models.statusAvailable": "可用",
  "dashboard.models.statusComingSoon": "即将上线",
  "dashboard.models.statusPaused": "暂停",
  "dashboard.models.subtitle": "查看 Tokfai 当前可用模型、能力、推荐场景和计费说明。",
  "dashboard.models.tableDesc": "用于 API 请求与 Playground 的 model ID。",
  "dashboard.models.tableTitle": "模型列表",
  "dashboard.models.title": "模型",
  "dashboard.models.usageTipsTitle": "使用建议",
  "dashboard.models.verificationUnavailableNote": "若实时验证暂时不可用，可先选定模型方案，稍后在接入工作台完成验证。",
  "dashboard.models.viewCreditsLedger": "查看积分账本",
  "dashboard.playground.apiKey": "API Key",
  "dashboard.playground.apiKeyLoadTimedOut": "加载所选 API Key 超时。请粘贴完整 secret 或稍后重试。",
  "dashboard.playground.copied": "已复制",
  "dashboard.playground.copyRequestId": "复制 request_id",
  "dashboard.playground.copySecret": "复制 secret",
  "dashboard.playground.costHint": "Playground 会消耗 credits，请先确认余额。实际扣费以积分账本为准。",
  "dashboard.playground.createdAt": "created_at",
  "dashboard.playground.createTestKey": "创建测试 Key",
  "dashboard.playground.creatingTestKey": "创建中…",
  "dashboard.playground.creditsCharged": "credits charged",
  "dashboard.playground.currentKeySelection": "当前选择：{name}（{prefix}…）",
  "dashboard.playground.errors.invalidToken": "API Key 无效或已吊销，请重新创建。",
  "dashboard.playground.errors.keyNotRetrievable": "出于安全考虑，完整 key 不会长期保存。请粘贴 key，或重新创建一个测试 Key。",
  "dashboard.playground.errors.missingPrompt": "请输入测试内容。",
  "dashboard.playground.errors.missingToken": "缺少 API Key，请先创建并选择可用密钥。",
  "dashboard.playground.errors.unknown": "请求失败，请稍后重试。",
  "dashboard.playground.errors.upstreamError": "当前模型暂时不可用或负载较高。",
  "dashboard.playground.forImageModels": "图像模型请使用",
  "dashboard.playground.fullApiKey": "完整 API Key",
  "dashboard.playground.goToApiKeys": "前往 API Keys",
  "dashboard.playground.hideKey": "隐藏",
  "dashboard.playground.inputTokens": "input tokens",
  "dashboard.playground.manageApiKeys": "管理 API Keys",
  "dashboard.playground.manageApiKeysHint": "如需吊销或删除密钥，请前往 API Keys 页面管理。",
  "dashboard.playground.model": "模型",
  "dashboard.playground.noKeyBody": "创建一个测试 Key 后，即可在 Playground 里完成第一次真实调用。",
  "dashboard.playground.noKeyTitle": "还没有可用 API Key",
  "dashboard.playground.outputTokens": "output tokens",
  "dashboard.playground.pasteKey": "粘贴密钥",
  "dashboard.playground.pasteKeySecurityHint": "密钥仅保存在当前页面 state，不会写入数据库。请勿在公共设备保存密钥。",
  "dashboard.playground.pasteOtherKey": "粘贴其他 Key",
  "dashboard.playground.productionKeyHint": "用于生产接入时，请在 API Keys 页面创建并复制 sk-tokfai 密钥。",
  "dashboard.playground.prompt": "Prompt",
  "dashboard.playground.promptPlaceholder": "请输入测试内容，例如：用一句话介绍 Tokfai API。",
  "dashboard.playground.request": "测试请求",
  "dashboard.playground.requestDesc": "选择或创建 API Key，选择对话模型，发送一条非流式消息进行测试。",
  "dashboard.playground.requestedModel": "请求 model",
  "dashboard.playground.requestId": "request_id",
  "dashboard.playground.requestStatus": "请求状态",
  "dashboard.playground.resolvedModel": "实际 model",
  "dashboard.playground.responseContent": "回复内容",
  "dashboard.playground.responsePlaceholder": "发送测试后，模型回复将显示在这里。",
  "dashboard.playground.resultTitle": "结果",
  "dashboard.playground.run": "发送测试",
  "dashboard.playground.running": "发送中…",
  "dashboard.playground.secretNotStored": "完整 secret 仅用于本次请求，不会保存在浏览器中。",
  "dashboard.playground.secretOnceHint": "完整 secret 只在创建时展示一次。刷新页面后将无法再次查看，如遗失请重新创建。",
  "dashboard.playground.selectKey": "选择密钥",
  "dashboard.playground.showKey": "显示",
  "dashboard.playground.statusFailed": "失败",
  "dashboard.playground.statusSuccess": "成功",
  "dashboard.playground.subtitle": "选择模型，发送一次测试请求，验证 Tokfai API 是否正常工作。",
  "dashboard.playground.successBalanceHint": "已记录至",
  "dashboard.playground.successReconcileHint": "复制 request_id，在 Usage 与 Credits 中搜索以核对本次调用。",
  "dashboard.playground.testKeyCreated": "测试 Key 已创建。请复制完整 secret；刷新页面后不会再次显示。",
  "dashboard.playground.testNow": "立即测试",
  "dashboard.playground.title": "Playground",
  "dashboard.playground.tokensNotReturned": "—",
  "dashboard.playground.totalTokens": "total tokens",
  "dashboard.playground.usageFallback": "本次消耗请以 /dashboard/credits 积分账本为准。",
  "dashboard.playground.viewChatApiDocs": "Chat API 文档",
  "dashboard.playground.viewCredits": "查看 Credits",
  "dashboard.playground.viewCreditsLedger": "查看积分账本",
  "dashboard.playground.viewDocs": "查看文档",
  "dashboard.playground.viewModels": "查看模型",
  "dashboard.playground.viewOpenAiSdkDocs": "OpenAI SDK 文档",
  "dashboard.playground.viewUsage": "查看 Usage",
  "dashboard.playground.waitingForModel": "等待模型响应…",
  "dashboard.shell.lowCredits": "积分较低",
  "dashboard.usage.copiedRequestId": "已复制",
  "dashboard.usage.copyRequestId": "复制 request_id",
  "dashboard.usage.loadingRecentRequests": "最近请求",
  "dashboard.usage.loadingRecentRequestsDesc": "正在加载最新用量记录…",
  "integration.apiKeyBulletAuthHeader": "请求头格式固定为 Authorization: Bearer sk-tokfai_xxx（xxx 替换为你的 secret）。",
  "integration.apiKeyBulletOneKeyAllApis": "一把 API Key 可用于 Chat API、Image API、Batch API——无需为每个模型单独创建密钥。",
  "integration.apiKeyBulletOneTime": "完整 secret 仅在创建密钥时展示一次——请立即复制保存。",
  "integration.apiKeyBulletReveal": "活跃密钥可在 API Keys 页面通过「复制密钥」（reveal）再次获取完整 secret。",
  "integration.apiKeyBulletRevoke": "密钥泄露后请立即 Revoke，并创建新密钥。",
  "integration.apiKeyBulletServerSide": "密钥只应放在服务端、脚本、IDE 或网关配置中——不要写入公开前端或公开源码。",
  "integration.apiKeyCopyNowTitle": "你现在就可以复制",
  "integration.apiReadiness.apiKeysHint": "若实时验证不可用，请妥善保存此密钥，并继续在接入工作台完成准备。",
  "integration.nav500OnlineReadiness": "500 人在线准备",
  "integration.navCapacityPlanner": "容量规划器",
  "integration.navRetryBackoff": "重试与退避",
  "integration.navTrafficGovernor": "流量治理",
  "integration.oneLineCurlPasteAnywhere": "复制后粘贴到任意终端即可。不需要安装，不需要进入项目目录。",
  "integration.starterTemplates.openLibrary": "打开接入模板库",
  "integration.trafficGovernor.scaleSafelyTitle": "安全扩容",
  "integration.troubleshooting.curlFailsTitle": "若 curl 失败",
  "integration.troubleshooting.invalidTokenGuide": "invalid_token 指南",
  "integration.troubleshooting.missingTokenGuide": "missing_token 指南",
  "integration.troubleshooting.openTroubleshooting": "打开故障排查",
  "quickstart.copied": "已复制",
  "quickstart.copy": "复制",
};
