/** Auto-generated — do not edit. Run: npx tsx scripts/generate-dashboard-labels.ts */

export type DashboardLocale = "en" | "zh";

export const EN: Record<string, string> = {
  "admin.adjust.addCredits": "Add credits",
  "admin.adjust.amount": "Amount",
  "admin.adjust.deductCredits": "Deduct credits",
  "admin.adjust.direction": "Direction",
  "admin.adjust.directionAdd": "Add",
  "admin.adjust.directionDeduct": "Deduct",
  "admin.adjust.email": "Email",
  "admin.adjust.invalidAmount": "Enter a positive amount.",
  "admin.adjust.missingReason": "Reason is required.",
  "admin.adjust.reason": "Reason",
  "admin.adjust.reasonPlaceholder": "Why this adjustment is being made",
  "admin.adjust.submit": "Submit adjustment",
  "admin.adjust.submitting": "Submitting…",
  "admin.adjust.subtitle": "Manual admin adjustment via DMIT /admin/credits/adjust.",
  "admin.adjust.success": "Adjustment applied. New balance: {balance} (delta {delta}).",
  "admin.adjust.title": "Adjust credits",
  "admin.adjust.userId": "Target user ID",
  "admin.announcements.formDesc": "Lower priority numbers appear earlier. Leave visibility empty for always-on.",
  "admin.announcements.loadFailed": "Failed to load announcements.",
  "admin.announcements.requiredFields": "Title and content are required.",
  "admin.announcements.saveFailed": "Failed to save announcement.",
  "admin.announcements.subtitle": "Create and manage dashboard announcements.",
  "admin.common.accessDenied": "Admin access denied",
  "admin.common.adminTools": "Admin tools",
  "admin.common.adminVerifyFailed": "Admin access could not be verified.",
  "admin.common.comingSoon": "Coming soon",
  "admin.common.notAuthorized": "Your account is not authorized for admin access.",
  "admin.common.readOnlyPhase": "Read-only in this phase",
  "admin.common.refresh": "Refresh",
  "admin.common.refreshing": "Refreshing…",
  "admin.common.retry": "Retry",
  "admin.common.sessionExpired": "Your session has expired. Please sign in again.",
  "admin.common.sessionExpiredTitle": "Session expired",
  "admin.common.signInAgain": "Sign in again",
  "admin.common.unknown": "unknown",
  "admin.common.verifyingAccess": "Verifying admin access",
  "admin.common.verifyingAccessDesc": "Confirming your session with the admin API…",
  "admin.credits.adjustmentStats": "Adjustments",
  "admin.credits.basedOnLoadedBatch": "Loaded batch only",
  "admin.credits.colAmount": "Amount",
  "admin.credits.colBalanceAfter": "Balance after",
  "admin.credits.colCreated": "Created",
  "admin.credits.colReason": "Reason",
  "admin.credits.colReference": "Reference",
  "admin.credits.colType": "Type",
  "admin.credits.currentBalance": "Current balance",
  "admin.credits.debitStats": "Debits",
  "admin.credits.email": "Email",
  "admin.credits.entryCount": "{count} entries",
  "admin.credits.groupStatsDesc": "Grouped totals from the 50 most recent ledger entries loaded for this account.",
  "admin.credits.groupStatsTitle": "Ledger breakdown",
  "admin.credits.lastUpdated": "Last updated",
  "admin.credits.ledgerEntries": "Ledger entries",
  "admin.credits.ledgerEntriesDesc": "Read-only view for {email}.",
  "admin.credits.noLedgerEntries": "No ledger entries for this user.",
  "admin.credits.noRecentDebits": "No debit entries in the loaded batch.",
  "admin.credits.noRecentTopups": "No top-up entries in the loaded batch.",
  "admin.credits.reasonAdminAdjustment": "Admin adjustment",
  "admin.credits.reasonChatUsage": "API usage debit",
  "admin.credits.reasonStripeTopUp": "Stripe top-up",
  "admin.credits.reasonSystemFix": "System correction",
  "admin.credits.recentDebits": "Recent debits",
  "admin.credits.recentDebitsDesc": "Latest usage debits from the loaded batch.",
  "admin.credits.recentTopups": "Recent top-ups",
  "admin.credits.recentTopupsDesc": "Latest credit-in entries from the loaded batch.",
  "admin.credits.refresh": "Refresh",
  "admin.credits.refreshing": "Refreshing…",
  "admin.credits.topupStats": "Top-ups",
  "admin.credits.totalUsed": "Total used",
  "admin.credits.viewUsageLogs": "View usage logs",
  "admin.debug.adminError": "Admin error",
  "admin.debug.apiBaseUrl": "API base URL",
  "admin.debug.currentUserEmail": "Current user email",
  "admin.debug.errorMessage": "Error message",
  "admin.debug.hasSessionToken": "Has session access token",
  "admin.debug.statusCode": "Status code",
  "admin.models.emptyFilters": "No models match the current filters.",
  "admin.models.filterAllStatuses": "All statuses",
  "admin.models.filterAllTypes": "All types",
  "admin.models.filterStatus": "Status",
  "admin.models.filterType": "Type",
  "admin.models.manage.addModel": "Add model",
  "admin.models.manage.archive": "Archive",
  "admin.models.manage.billingChat": "chat",
  "admin.models.manage.billingImage": "image",
  "admin.models.manage.cancel": "Cancel",
  "admin.models.manage.createModel": "Create model",
  "admin.models.manage.createTitle": "Create model",
  "admin.models.manage.edit": "Edit",
  "admin.models.manage.editTitle": "Edit model",
  "admin.models.manage.formBillingType": "Billing type",
  "admin.models.manage.formDisplayName": "Display name",
  "admin.models.manage.formEnabled": "Model enabled",
  "admin.models.manage.formId": "Model ID",
  "admin.models.manage.formImageCredits": "Credits / generation",
  "admin.models.manage.formInputPerMillion": "Input credits / 1M tokens",
  "admin.models.manage.formMarkupRatio": "Markup ratio (optional)",
  "admin.models.manage.formOutputPerMillion": "Output credits / 1M tokens",
  "admin.models.manage.formPricingEnabled": "Pricing enabled",
  "admin.models.manage.formPricingPreviewOnlyNotice": "This model or its pricing is not fully enabled. Values below are for admin preview only — users cannot use or purchase this model yet.",
  "admin.models.manage.formPricingVisible": "Pricing visible on dashboard",
  "admin.models.manage.formProvider": "Provider",
  "admin.models.manage.formSortOrder": "Sort order",
  "admin.models.manage.formType": "Type",
  "admin.models.manage.formUpstreamNote": "Upstream cost note (admin only)",
  "admin.models.manage.formUpstreamNoteHint": "Internal note — never shown to users",
  "admin.models.manage.formVideoUnavailableNotice": "Video model is not enabled yet. Per-generation credits and CNY examples are informational only and do not imply availability.",
  "admin.models.manage.formVisible": "Model visible",
  "admin.models.manage.loadFailed": "Failed to load models.",
  "admin.models.manage.loadFailedTitle": "Could not load models",
  "admin.models.manage.loading": "Loading models…",
  "admin.models.manage.pricePreviewDisclaimer": "CNY examples are illustrative conversions from recharge tiers only. Actual cost depends on the user's package and final usage records.",
  "admin.models.manage.restore": "Restore",
  "admin.models.manage.saveChanges": "Save changes",
  "admin.models.manage.saving": "Saving…",
  "admin.models.manage.statusArchived": "archived",
  "admin.models.manage.statusDisabled": "disabled",
  "admin.models.manage.subtitle": "Manage catalog models and pricing via DMIT. Billing still uses existing usage and credit flows.",
  "admin.models.manage.syncCatalog": "Sync missing models",
  "admin.models.manage.syncing": "Syncing…",
  "admin.models.manage.syncSuccess": "Catalog sync complete. Inserted {models} models, {pricing} pricing rows. Skipped {skipped} existing.",
  "admin.models.manage.tableBilling": "Billing type",
  "admin.models.manage.tableDesc": "Showing {count} models from DMIT.",
  "admin.models.manage.tablePricePreview": "Price example",
  "admin.models.manage.tablePricing": "Pricing",
  "admin.models.manage.tableTitle": "Models",
  "admin.models.manage.tableUpdated": "Updated",
  "admin.models.manage.title": "Model management",
  "admin.models.manage.typeOther": "other",
  "admin.models.searchFilters": "Search & filters",
  "admin.models.searchLabel": "Search model name or model ID",
  "admin.models.searchPlaceholder": "e.g. gemini-3.1-pro",
  "admin.models.statusAvailable": "available",
  "admin.models.statusComingSoon": "coming soon",
  "admin.models.subtitle": "Manage catalog models and pricing. Actual charges are still recorded in Usage and Credits.",
  "admin.models.tableModelId": "Model ID",
  "admin.models.tableModelName": "Model name",
  "admin.models.tableStatus": "Status",
  "admin.models.tableType": "Type",
  "admin.models.title": "Models & pricing",
  "admin.models.typeChat": "chat",
  "admin.models.typeImage": "image",
  "admin.models.typeVideo": "video",
  "admin.nav.backToDashboard": "Back to dashboard",
  "admin.nav.sections": "Admin sections",
  "admin.rechargePlans.archive": "Archive",
  "admin.rechargePlans.archived": "Plan archived.",
  "admin.rechargePlans.archivedBadge": "Archived",
  "admin.rechargePlans.cancel": "Cancel",
  "admin.rechargePlans.checkoutHint": "Checkout and webhooks credit accounts using the credits column only.",
  "admin.rechargePlans.colActions": "Actions",
  "admin.rechargePlans.colAmount": "Price",
  "admin.rechargePlans.colArchived": "Archived",
  "admin.rechargePlans.colBadge": "Badge",
  "admin.rechargePlans.colBaseCredits": "Base credits",
  "admin.rechargePlans.colBonusCredits": "Bonus credits",
  "admin.rechargePlans.colCredits": "Credits (total)",
  "admin.rechargePlans.colDescription": "Description",
  "admin.rechargePlans.colEnabled": "Checkout enabled",
  "admin.rechargePlans.colId": "ID",
  "admin.rechargePlans.colName": "Name",
  "admin.rechargePlans.colSortOrder": "Sort order",
  "admin.rechargePlans.colStripePriceId": "Stripe price ID",
  "admin.rechargePlans.colUpdated": "Updated",
  "admin.rechargePlans.colVisible": "Visible",
  "admin.rechargePlans.create": "Create",
  "admin.rechargePlans.created": "Recharge plan created.",
  "admin.rechargePlans.createFailed": "Failed to create recharge plan.",
  "admin.rechargePlans.createPlan": "Create plan",
  "admin.rechargePlans.createTitle": "New recharge plan",
  "admin.rechargePlans.creating": "Creating…",
  "admin.rechargePlans.creditsComputedHint": "Credits (total) is read-only — it equals base credits + bonus credits.",
  "admin.rechargePlans.disableCheckout": "Disable checkout",
  "admin.rechargePlans.duplicate": "Duplicate",
  "admin.rechargePlans.duplicated": "Plan duplicated as {id}.",
  "admin.rechargePlans.edit": "Edit",
  "admin.rechargePlans.empty": "No recharge plans found.",
  "admin.rechargePlans.enableCheckout": "Enable checkout",
  "admin.rechargePlans.hideFromPricing": "Hide from pricing",
  "admin.rechargePlans.loadFailed": "Failed to load recharge plans.",
  "admin.rechargePlans.no": "No",
  "admin.rechargePlans.restored": "Plan restored.",
  "admin.rechargePlans.save": "Save",
  "admin.rechargePlans.saved": "Recharge plan saved.",
  "admin.rechargePlans.saveFailed": "Failed to save recharge plan.",
  "admin.rechargePlans.saving": "Saving…",
  "admin.rechargePlans.showArchived": "Show archived",
  "admin.rechargePlans.showOnPricing": "Show on pricing",
  "admin.rechargePlans.subtitle": "Create and manage recharge packages. Final credits are computed as base + bonus on the server.",
  "admin.rechargePlans.tableDesc": "Changes apply to pricing and checkout after save. Checkout still sends plan_id only.",
  "admin.rechargePlans.tableTitle": "Plan catalog",
  "admin.rechargePlans.title": "Recharge plans",
  "admin.rechargePlans.unarchive": "Unarchive",
  "admin.rechargePlans.yes": "Yes",
  "admin.usage.colCompletion": "Completion",
  "admin.usage.colCreated": "Created",
  "admin.usage.colCredits": "Credits",
  "admin.usage.colEmail": "Email",
  "admin.usage.colModel": "Model",
  "admin.usage.colPrompt": "Prompt",
  "admin.usage.colRequestId": "Request ID",
  "admin.usage.colStatus": "Status",
  "admin.usage.colTotal": "Total",
  "admin.usage.empty": "No usage logs found.",
  "admin.users.actions": "Actions",
  "admin.users.createdAt": "Created",
  "admin.users.creditsBalance": "Credits balance",
  "admin.users.email": "Email",
  "admin.users.hideDetails": "Hide details",
  "admin.users.ledger": "Ledger",
  "admin.users.noUsers": "No user profiles found.",
  "admin.users.subtitle": "Account overview with balances, purchase totals, usage totals, and credit adjustments.",
  "admin.users.title": "User management",
  "admin.users.totalCreditsPurchased": "Total purchased",
  "admin.users.totalCreditsUsed": "Total used",
  "admin.users.updatedAt": "Updated",
  "admin.users.userDetailTitle": "Account details",
  "admin.users.userManagement": "User management",
  "admin.users.userManagementDesc": "Browse email, user_id, credit balance, lifetime purchases, and usage. Use Add/Deduct credits for manual adjustments.",
  "admin.users.userProfiles": "User profiles",
  "admin.users.userProfilesDesc": "{count} accounts from the admin users endpoint.",
  "admin.users.viewDetails": "View details",
  "admin.users.viewRecentLedger": "View ledger",
  "admin.users.viewRecentUsage": "View recent usage",
  "auth.success.accountCreated": "Account created. You're all set!",
  "auth.success.dismiss": "Dismiss",
  "auth.success.welcomeBack": "You're signed in. Welcome back!",
  "common.chatPlayground": "Chat Playground",
  "common.footerTagline": "Tokfai · OpenAI-compatible image & chat API",
  "common.imagePlayground": "Image Playground",
  "common.open": "Open",
  "common.signedInAs": "Signed in as",
  "common.signingOut": "Signing out…",
  "common.signOut": "Sign out",
  "common.unavailable": "Unavailable",
  "dashboard.announcements.announcementContent": "Content",
  "dashboard.announcements.announcements": "Announcements",
  "dashboard.announcements.announcementSaved": "Announcement saved.",
  "dashboard.announcements.announcementTitle": "Title",
  "dashboard.announcements.announcementType": "Type",
  "dashboard.announcements.editAnnouncement": "Edit announcement",
  "dashboard.announcements.enabled": "Enabled",
  "dashboard.announcements.latestAnnouncements": "Latest announcements",
  "dashboard.announcements.newAnnouncement": "New announcement",
  "dashboard.announcements.noAnnouncements": "No announcements yet.",
  "dashboard.announcements.pinned": "Pinned",
  "dashboard.announcements.subtitle": "System notices, maintenance windows, and usage guides.",
  "dashboard.announcements.viewAll": "View all",
  "dashboard.announcements.visibleFrom": "Visible from",
  "dashboard.announcements.visibleUntil": "Visible until",
  "dashboard.apiKeys.active": "Active",
  "dashboard.apiKeys.apiKeyCreated": "API key created",
  "dashboard.apiKeys.apiKeyCreatedNamed": "API key created: {name}",
  "dashboard.apiKeys.apiKeyUnderstandingDesc": "Your credential to call Tokfai APIs — same rules as the API Key chapter in Docs.",
  "dashboard.apiKeys.apiKeyUnderstandingTitle": "What is a Tokfai API Key?",
  "dashboard.apiKeys.authHeaderHint": "Use this key in",
  "dashboard.apiKeys.buildPayload": "Build payload",
  "dashboard.apiKeys.buildStarterTemplate": "Build starter template",
  "dashboard.apiKeys.capacityRateLimitsLink": "Capacity & rate limits",
  "dashboard.apiKeys.cherryStudioGuide": "Cherry Studio guide",
  "dashboard.apiKeys.colActions": "Actions",
  "dashboard.apiKeys.colCreated": "Created",
  "dashboard.apiKeys.colLastUsed": "Last used",
  "dashboard.apiKeys.colName": "Name",
  "dashboard.apiKeys.colPrefix": "Prefix",
  "dashboard.apiKeys.colRevokedAt": "Revoked at",
  "dashboard.apiKeys.colStatus": "Status",
  "dashboard.apiKeys.commercialFaqGuide": "Commercial FAQ",
  "dashboard.apiKeys.copied": "Copied",
  "dashboard.apiKeys.copyAuthHeader": "Copy Authorization header",
  "dashboard.apiKeys.copyCherryConfig": "Copy Cherry config",
  "dashboard.apiKeys.copyCursorConfig": "Copy Cursor config",
  "dashboard.apiKeys.copyFullKey": "Copy full key",
  "dashboard.apiKeys.copying": "Copying...",
  "dashboard.apiKeys.copyKey": "Copy key",
  "dashboard.apiKeys.copyNodeSdkConfig": "Copy Node.js SDK config",
  "dashboard.apiKeys.copyOneLineChatCurl": "Copy one-line Chat curl",
  "dashboard.apiKeys.copyOneLineModelsCurl": "Copy one-line Models curl",
  "dashboard.apiKeys.copyPowerShellChatCurl": "Copy PowerShell Chat curl",
  "dashboard.apiKeys.copyPythonSdkConfig": "Copy Python SDK config",
  "dashboard.apiKeys.createApiKey": "Create API key",
  "dashboard.apiKeys.createApiKeyDesc": "Optional name for your reference. Leave blank to use the default name.",
  "dashboard.apiKeys.creating": "Creating...",
  "dashboard.apiKeys.cursorGuide": "Cursor guide",
  "dashboard.apiKeys.emptyCreateFirst": "Create your first API key",
  "dashboard.apiKeys.emptyRecharge": "Top up credits",
  "dashboard.apiKeys.emptyTitle": "No API keys yet. Create your first key to start testing — the full secret is shown once, so copy it immediately.",
  "dashboard.apiKeys.errorCode": "Code",
  "dashboard.apiKeys.errorHttpStatus": "HTTP status",
  "dashboard.apiKeys.errorRequestId": "request_id",
  "dashboard.apiKeys.goToCredits": "Go to Credits",
  "dashboard.apiKeys.goToUsage": "Go to Usage",
  "dashboard.apiKeys.integrationLinksTitle": "Try and verify",
  "dashboard.apiKeys.integrationWorkbench": "Integration workbench",
  "dashboard.apiKeys.keyName": "Key name",
  "dashboard.apiKeys.keyNamePlaceholder": "e.g. production",
  "dashboard.apiKeys.keyReadyMessage": "Your key is ready. Verify one request first, then plan capacity and hand off integration.",
  "dashboard.apiKeys.largeVolumeBatchGuide": "Large-volume Batch guide",
  "dashboard.apiKeys.largeVolumeIntegrationLink": "Large-volume integration",
  "dashboard.apiKeys.listUnavailableDesc": "The key list could not load — the API may be temporarily unavailable. You can still create a new key below, or retry after a few minutes.",
  "dashboard.apiKeys.listUnavailableTitle": "Could not load your API keys",
  "dashboard.apiKeys.loadError": "Could not load API keys",
  "dashboard.apiKeys.loadErrorAuthDesc": "Your session has expired. Please sign in again.",
  "dashboard.apiKeys.loadErrorTempDesc": "Unable to load API keys. Please try again later.",
  "dashboard.apiKeys.neverUsed": "Never used",
  "dashboard.apiKeys.nextStepBatch": "Batch API is in the Batch chapter in Docs.",
  "dashboard.apiKeys.nextStepCherry": "Cherry Studio setup is in the Cherry chapter in Docs.",
  "dashboard.apiKeys.nextStepCurl": "Copy one-line models curl to verify auth, or one-line chat curl for a full test (same as Docs API Key chapter).",
  "dashboard.apiKeys.nextStepCursor": "Cursor setup is in the Cursor chapter in Docs.",
  "dashboard.apiKeys.nextStepSdk": "See Docs for OpenAI SDK, Cursor, and Cherry Studio.",
  "dashboard.apiKeys.nextStepsTitle": "Connect via Tokfai API",
  "dashboard.apiKeys.oneTimeSecretDesc": "Copy and store this key now — it is shown only once at creation.",
  "dashboard.apiKeys.online500Guide": "500 online users guide",
  "dashboard.apiKeys.openStarterTemplates": "Open Starter Templates",
  "dashboard.apiKeys.pasteTerminalNote": "Paste and run in any terminal. No repo, no install, no cd.",
  "dashboard.apiKeys.productionHandoffTitle": "Production handoff",
  "dashboard.apiKeys.productionUseGuide": "Production use",
  "dashboard.apiKeys.quickStartDocs": "Quick start guide",
  "dashboard.apiKeys.retryBackoffGuide": "Retry & backoff guide",
  "dashboard.apiKeys.retryRateLimitGuide": "Retry & rate limit guide",
  "dashboard.apiKeys.revoke": "Revoke",
  "dashboard.apiKeys.revokeConfirm": "Revoke this API key? Existing apps using this key will stop working. This cannot be undone.",
  "dashboard.apiKeys.revoked": "Revoked",
  "dashboard.apiKeys.revoking": "Revoking...",
  "dashboard.apiKeys.savedMyKey": "I've saved my key",
  "dashboard.apiKeys.securityDesc": "Treat API keys like passwords. Never expose them in client-side code or public source code.",
  "dashboard.apiKeys.securityItem1": "Store keys on your server only — never embed them in mobile apps, browsers, or public frontends.",
  "dashboard.apiKeys.securityItem2": "If a key is leaked or exposed, revoke it immediately and create a replacement.",
  "dashboard.apiKeys.securityItem3": "The full secret is shown once at creation. After that, use Copy key on active keys to copy the full secret again.",
  "dashboard.apiKeys.securityItem4": "One API Key works for Chat, Image, and Batch — you do not need separate keys per model.",
  "dashboard.apiKeys.securityItem5": "If a key is leaked or exposed, Revoke it immediately and create a replacement.",
  "dashboard.apiKeys.securityTitle": "Keep your keys secure",
  "dashboard.apiKeys.sessionKeyDocsNote": "After you save your key, this browser session still fills Docs examples. Refreshing clears it — copy your key or one-line curl again if you see a placeholder.",
  "dashboard.apiKeys.startIntegration": "Start integration",
  "dashboard.apiKeys.startIntegrationWorkbench": "Start Integration Workbench",
  "dashboard.apiKeys.storeBackendSecurityNote": "Store your API Key on your backend. Do not expose it in browser frontend.",
  "dashboard.apiKeys.subtitleCreate": "Create keys to authenticate requests to {baseUrl}. The full secret is shown once when created. Active keys can be revealed and copied again with Copy key.",
  "dashboard.apiKeys.subtitleMeta": "View API key metadata for your Tokfai account.",
  "dashboard.apiKeys.title": "API Keys",
  "dashboard.apiKeys.verifyCredits": "Verify in Credits",
  "dashboard.apiKeys.verifyUsage": "Verify in Usage",
  "dashboard.apiKeys.viewApiDocs": "View API docs",
  "dashboard.apiKeys.viewApiKeyDocs": "API Key docs",
  "dashboard.apiKeys.viewDocs": "View docs",
  "dashboard.apiKeys.viewUsageCreditsDocs": "Usage & Credits guide",
  "dashboard.apiKeys.yourApiKey": "Your API key",
  "dashboard.apiKeys.yourApiKeys": "Your API keys",
  "dashboard.apiKeys.yourApiKeysDesc": "Prefixes are shown for identification. Use Copy key to copy the full secret for active keys.",
  "dashboard.credits.actionApiKeys": "API keys",
  "dashboard.credits.actionDocs": "Quickstart docs",
  "dashboard.credits.actionRecharge": "Recharge credits",
  "dashboard.credits.checkoutCancelled": "Checkout was cancelled",
  "dashboard.credits.checkoutCancelledDesc": "No credits were added. You can pick another package on Pricing.",
  "dashboard.credits.colAmount": "Amount",
  "dashboard.credits.colBalanceAfter": "Balance after",
  "dashboard.credits.colCreated": "Created",
  "dashboard.credits.colPlan": "Plan",
  "dashboard.credits.colReason": "Reason",
  "dashboard.credits.colReference": "Reference",
  "dashboard.credits.colSession": "Checkout session",
  "dashboard.credits.colStatus": "Status",
  "dashboard.credits.colType": "Type",
  "dashboard.credits.copiedReference": "Copied",
  "dashboard.credits.copyReference": "Copy reference",
  "dashboard.credits.createApiKey": "Create API key",
  "dashboard.credits.currentBalance": "Current balance",
  "dashboard.credits.emptyLedger": "No ledger entries yet. Top up on Pricing, create an API key, then run a Playground test — top-ups and usage debits will appear here.",
  "dashboard.credits.emptyLedgerTopUp": "Top up credits",
  "dashboard.credits.emptyOrders": "No recharge orders yet.",
  "dashboard.credits.howItWorksItem1": "Your balance and totals on this page match Usage and Credits records — they are the source of truth.",
  "dashboard.credits.howItWorksItem2": "Chat API (POST /v1/chat/completions) is billed by input and output tokens.",
  "dashboard.credits.howItWorksItem3": "Image API (POST /v1/images/generations) is billed per successful generation.",
  "dashboard.credits.howItWorksItem4": "Playground and API calls charge credits only after a successful response.",
  "dashboard.credits.howItWorksItem5": "Failed requests are not charged.",
  "dashboard.credits.howItWorksItem6": "The Credits ledger is the authoritative record of balance changes; debits follow successful requests.",
  "dashboard.credits.howItWorksTitle": "How credits work",
  "dashboard.credits.integrationWorkbenchLink": "Integration Workbench",
  "dashboard.credits.last7DaysConsumed": "Consumed (7 days)",
  "dashboard.credits.lastChange": "Last change",
  "dashboard.credits.loadErrorAuth": "Session expired — please sign in again",
  "dashboard.credits.loadErrorAuthDesc": "Your session has expired. Please sign in again.",
  "dashboard.credits.loadErrorTemp": "Credits unavailable",
  "dashboard.credits.loadErrorTempDesc": "Credits could not be loaded right now. Please try again later.",
  "dashboard.credits.noLedgerForReference": "No ledger rows match this reference in the loaded entries. Widen your search or confirm the API call succeeded.",
  "dashboard.credits.noLedgerHint": "No credit ledger entries yet.",
  "dashboard.credits.orderExpiredDesc": "This checkout session was not finished in time. Start a new recharge on Pricing if you still want credits.",
  "dashboard.credits.orderExpiredTitle": "Checkout not completed",
  "dashboard.credits.orderPaidDesc": "This checkout is paid and credits have been added to your balance.",
  "dashboard.credits.orderPaidTitle": "Top-up completed",
  "dashboard.credits.paymentReceived": "Payment received",
  "dashboard.credits.paymentReceivedDesc": "Payment received. Credits are added automatically after Stripe confirms checkout (usually within seconds). Refresh this page if your balance has not updated yet.",
  "dashboard.credits.quickActions": "Quick actions",
  "dashboard.credits.reasonAdminAdjustment": "Admin adjustment",
  "dashboard.credits.reasonChatUsage": "Chat API usage",
  "dashboard.credits.reasonImageUsage": "Image generation",
  "dashboard.credits.reasonStripeCheckout": "Stripe top-up",
  "dashboard.credits.reasonSystemFix": "System correction",
  "dashboard.credits.recentLedger": "Credit ledger",
  "dashboard.credits.recentLedgerDesc": "Last 50 entries, newest first.",
  "dashboard.credits.recentOrders": "Recharge orders",
  "dashboard.credits.recentOrdersDesc": "Last 10 Stripe Checkout orders. Pending orders older than 24 hours show as expired.",
  "dashboard.credits.referenceFilterOptional": "Reference / request_id (optional)",
  "dashboard.credits.subtitle": "View your balance, recharge orders, and API usage debit history.",
  "dashboard.credits.title": "Credits ledger",
  "dashboard.credits.todayConsumed": "Consumed today",
  "dashboard.firstRun.allComplete": "First-run setup complete — your key, test call, and usage trail are ready.",
  "dashboard.firstRun.checkUsage": "Check Usage",
  "dashboard.firstRun.cherryGuide": "View Cherry Studio guide",
  "dashboard.firstRun.createApiKey": "Create API key",
  "dashboard.firstRun.cursorGuide": "View Cursor guide",
  "dashboard.firstRun.desc": "Create API Key → copy one-line curl → paste in any terminal → reconcile in Usage and Credits.",
  "dashboard.firstRun.integrationWorkbench": "Integration Workbench",
  "dashboard.firstRun.quickStart": "Quick Start curl",
  "dashboard.firstRun.title": "Get started in about 3 minutes",
  "dashboard.firstRun.tryPlayground": "Try Chat Playground",
  "dashboard.firstRun.viewIntegrationDocs": "View integration docs",
  "dashboard.imagePlayground.addImageUrl": "Add URL",
  "dashboard.imagePlayground.base64OnlyHint": "The API returned base64 image data (data[0].b64_json). Image Playground only previews URL responses — use the API directly or set response_format=url.",
  "dashboard.imagePlayground.copiedRequestId": "Copied",
  "dashboard.imagePlayground.copyApiRequest": "Copy API request",
  "dashboard.imagePlayground.copyRequestId": "Copy request ID",
  "dashboard.imagePlayground.createApiKey": "Create an API key",
  "dashboard.imagePlayground.createTestKey": "Create test key",
  "dashboard.imagePlayground.errors.billingNotChargedHint": "Failed requests are usually not charged. See Usage / Credits for the official record.",
  "dashboard.imagePlayground.errors.invalidDrop": "Drop PNG, JPG, or WEBP image files.",
  "dashboard.imagePlayground.errors.invalidToken": "API key is invalid or revoked. Create a new key.",
  "dashboard.imagePlayground.errors.keyNotRetrievable": "For security, full keys aren't stored long-term. Paste your key or create a new test key.",
  "dashboard.imagePlayground.errors.missingPrompt": "Please enter a prompt.",
  "dashboard.imagePlayground.errors.missingToken": "Missing API key. Create and paste an active key first.",
  "dashboard.imagePlayground.errors.pageImageNotFound": "Could not find a usable image on this page. Try another URL or upload the image directly.",
  "dashboard.imagePlayground.errors.tooManyImages": "Up to {max} input images are allowed.",
  "dashboard.imagePlayground.errors.unknown": "Request failed. Please try again later.",
  "dashboard.imagePlayground.estimatedCost": "Estimated cost: {credits} credits",
  "dashboard.imagePlayground.generate": "Generate",
  "dashboard.imagePlayground.generating": "Generating…",
  "dashboard.imagePlayground.imageToImage": "Image to Image",
  "dashboard.imagePlayground.inputImagesDesc": "Drag, upload, or paste URLs. Up to {max} images (PNG, JPG, WEBP). Leave empty for text-to-image.",
  "dashboard.imagePlayground.inputImagesDragHint": "PNG, JPG, WEBP · max 10 MB each",
  "dashboard.imagePlayground.inputImagesDragTitle": "Drag images here or click to upload",
  "dashboard.imagePlayground.inputImagesTitle": "Input images",
  "dashboard.imagePlayground.inputImagesUrlPlaceholder": "Image or page URL — Tokfai extracts the image when possible",
  "dashboard.imagePlayground.metaCreatedAt": "Created at",
  "dashboard.imagePlayground.metaModel": "Model",
  "dashboard.imagePlayground.modelComingSoon": "This model is coming soon and cannot be used in Playground yet.",
  "dashboard.imagePlayground.preparingImages": "Preparing input images…",
  "dashboard.imagePlayground.size": "Size",
  "dashboard.imagePlayground.successCreditsCharged": "Charged {credits} credits.",
  "dashboard.imagePlayground.successReconcileHint": "Copy request_id and search it in Usage and Credits to reconcile this generation.",
  "dashboard.imagePlayground.textToImage": "Text to Image",
  "dashboard.imagePlayground.title": "Image Playground",
  "dashboard.imagePlayground.toolbenchApiKeyLabel": "API Key",
  "dashboard.imagePlayground.toolbenchBalanceLabel": "Balance",
  "dashboard.imagePlayground.toolbenchBillingNoteShort": "Successful generations are charged. Failed calls are usually not charged.",
  "dashboard.imagePlayground.toolbenchCurrentKeyLine": "Current: {name} · {prefix}…",
  "dashboard.imagePlayground.toolbenchInputTitle": "Input",
  "dashboard.imagePlayground.toolbenchInsufficientCredits": "Insufficient credits — top up before generating.",
  "dashboard.imagePlayground.toolbenchManageKeysShort": "Manage",
  "dashboard.imagePlayground.toolbenchModelLabel": "Model",
  "dashboard.imagePlayground.toolbenchNoKey": "Create an API Key to call the Image API from your account.",
  "dashboard.imagePlayground.toolbenchOpenIntegrationDocs": "Open integration docs",
  "dashboard.imagePlayground.toolbenchPasteKeyShort": "Paste key",
  "dashboard.imagePlayground.toolbenchResultLoadingHint": "Keep this panel visible. The result will appear here.",
  "dashboard.imagePlayground.toolbenchResultLoadingTitle": "Generating…",
  "dashboard.imagePlayground.toolbenchResultPanelTitle": "Result",
  "dashboard.imagePlayground.toolbenchResultPlaceholder": "Generated image will appear here",
  "dashboard.imagePlayground.toolbenchRetry": "Retry",
  "dashboard.imagePlayground.toolbenchRunSettings": "Run settings",
  "dashboard.imagePlayground.toolbenchServiceDocs": "Service docs",
  "dashboard.imagePlayground.toolbenchSubtitle": "Prompt → optional reference images → Generate. Charged only on successful API responses.",
  "dashboard.imagePlayground.toolbenchViewImageApiDocs": "View Image API docs",
  "dashboard.imagePlayground.topUp": "Top up",
  "dashboard.imagePlayground.viewCredits": "View Credits",
  "dashboard.imagePlayground.viewImageApiDocs": "Image API docs",
  "dashboard.imagePlayground.viewUsage": "View Usage",
  "dashboard.imagePlayground.waitingForImages": "Waiting for input images to finish uploading or resolving…",
  "dashboard.models.buildPayloadAutoCheap": "Build payload — ecommerce batch",
  "dashboard.models.buildPayloadAutoFast": "Build payload — general/support chat",
  "dashboard.models.buildPayloadAutoPro": "Build payload — hospital/auto quality",
  "dashboard.models.buildPayloadImage": "Build payload — image",
  "dashboard.models.buildPayloadWithModel": "Build payload with this model",
  "dashboard.models.buildTemplateAutoCheap": "Build template — auto-cheap batch",
  "dashboard.models.buildTemplateAutoFast": "Build template — auto-fast chat",
  "dashboard.models.buildTemplateAutoPro": "Build template — auto-pro quality",
  "dashboard.models.buildTemplateImage": "Build template — gpt-image-2 image",
  "dashboard.models.buildTemplateWithModel": "Build template with this model",
  "dashboard.models.capacityPlannerLink": "Capacity planner",
  "dashboard.models.colApproxRmb": "Budget reference",
  "dashboard.models.colLongEstimate": "Long analysis / plan usage",
  "dashboard.models.colModelId": "Model ID",
  "dashboard.models.colPackageCredits": "Credits included",
  "dashboard.models.colPackagePlan": "Plan",
  "dashboard.models.colPackageUsageFit": "Typical fit",
  "dashboard.models.colShortEstimate": "Short chat / per image",
  "dashboard.models.colStatus": "Status",
  "dashboard.models.colType": "Type",
  "dashboard.models.copied": "Copied",
  "dashboard.models.copyCurlWithModel": "Copy one-line curl with this model",
  "dashboard.models.copyModelId": "Copy model id",
  "dashboard.models.exampleDesc": "For a real one-line curl with your key, copy from API Keys or Docs Quick Start. Example below uses a placeholder.",
  "dashboard.models.exampleTitle": "Minimal request",
  "dashboard.models.footerActions": "Next steps",
  "dashboard.models.footerApiKeys": "Create API key",
  "dashboard.models.footerCapacityGuide": "Capacity & rate limits",
  "dashboard.models.footerCredits": "Credits ledger",
  "dashboard.models.footerDocs": "View integration docs",
  "dashboard.models.footerHighTrafficBatch": "High traffic — Batch & capacity",
  "dashboard.models.footerIndustryTemplates": "Industry templates",
  "dashboard.models.footerPlayground": "Open Playground",
  "dashboard.models.footerProductionUse": "Production use",
  "dashboard.models.footerQuickStart": "Quick Start curl",
  "dashboard.models.footerRateLimits": "Rate limits",
  "dashboard.models.footerStartIntegration": "Start integration",
  "dashboard.models.footerUsage": "Check Usage",
  "dashboard.models.goLiveAutoCheapEcommerce": "Use auto-cheap for high-volume ecommerce copy",
  "dashboard.models.goLiveAutoFastFirst": "Use auto-fast for first test",
  "dashboard.models.goLiveAutoProQuality": "Use auto-pro for quality workloads",
  "dashboard.models.goLiveChooseModelPlan": "Choose model plan in capacity planner",
  "dashboard.models.goLiveOpenTracker": "Open go-live tracker",
  "dashboard.models.goLiveReadinessTitle": "Go-live readiness",
  "dashboard.models.highTrafficBatchGovernor": "High traffic: use Batch API and traffic governor with safe retry.",
  "dashboard.models.highTrafficBatchItems": "Batch: 500–1,000 items per job — async queue with polling.",
  "dashboard.models.highTrafficBatchNote": "High traffic? Use Batch API and the capacity guide for controlled concurrency.",
  "dashboard.models.highTrafficCapacityPlanner": "Use the capacity planner to pick concurrency, model, and Batch vs Chat split.",
  "dashboard.models.highTrafficChatConcurrency": "Chat: 25–50 controlled concurrent sync requests per app.",
  "dashboard.models.highTrafficClientQueue": "Use a client-side queue and concurrency governor; large jobs use Batch worker.",
  "dashboard.models.highTrafficImageConcurrency": "Image: 5–15 controlled concurrent requests (slow generation).",
  "dashboard.models.highTrafficIntegrationTitle": "High traffic integration",
  "dashboard.models.highTrafficNoInfiniteRetry": "Do not retry forever on 429 / 503 / 504 — cap attempts and use backoff.",
  "dashboard.models.highTrafficOnline500Note": "500 online does not mean 500 simultaneous upstream calls — use client-side queue limits.",
  "dashboard.models.highTrafficReconcile": "Reconcile every request_id in Usage and Credits (reference_id on ledger).",
  "dashboard.models.highTrafficUseBatch": "Use Batch API for large volume instead of sync Chat floods.",
  "dashboard.models.howToEstimateTitle": "How to estimate call cost?",
  "dashboard.models.inputPrice": "Input",
  "dashboard.models.listDisclaimer": "The model list is updated continuously.",
  "dashboard.models.openIntegrationWorkbench": "Open Integration Workbench",
  "dashboard.models.openUsageCreditsGuide": "Usage / Credits guide",
  "dashboard.models.outputPrice": "Output",
  "dashboard.models.overviewChat": "Chat models",
  "dashboard.models.overviewDefault": "Default model",
  "dashboard.models.overviewImage": "Image models",
  "dashboard.models.overviewTotal": "Available models",
  "dashboard.models.packageEstimateDesc": "Illustrative fit for {model} (chat) and {imageModel} (images). Not a usage guarantee.",
  "dashboard.models.packageEstimateRoughNote": "Rough guide only. Actual usable volume varies with model, prompt length, image size, and retries.",
  "dashboard.models.packageEstimateTitle": "Package usage reference",
  "dashboard.models.priceDisclaimer": "Budget reference: 1 yuan ≈ 1,000 credits (1 credit ≈ ¥0.001).",
  "dashboard.models.priceDisclaimerBudget": "Figures below are for budgeting only. Actual charges follow Usage and Credits ledger records.",
  "dashboard.models.priceDisclaimerTitle": "Price estimate disclaimer",
  "dashboard.models.productionGuidanceAutoCheap": "auto-cheap — low-cost batch-style workloads.",
  "dashboard.models.productionGuidanceAutoFast": "auto-fast — default recommendation for go-live smoke tests and general traffic.",
  "dashboard.models.productionGuidanceAutoPro": "auto-pro — higher-quality tasks when you need stronger reasoning.",
  "dashboard.models.productionGuidanceBatchNote": "Large volume jobs: prefer Batch API and reconcile each request_id in Usage / Credits.",
  "dashboard.models.productionGuidanceExplicit": "Explicit model IDs — for advanced customers who understand upstream trade-offs.",
  "dashboard.models.productionGuidanceTitle": "Production model strategy",
  "dashboard.models.recommendedStartingModel": "Recommended starting model: auto-fast",
  "dashboard.models.recommendedUseCase": "Best for",
  "dashboard.models.salesTip": "Start with a small package to complete integration testing. Confirm model, quality, and consumption before scaling volume.",
  "dashboard.models.scaleSafelyTitle": "Scale safely",
  "dashboard.models.smartRoutingDesc": "Use auto-* aliases for a stable entry point. Tokfai tries upstream models in order and returns the model that actually succeeded.",
  "dashboard.models.smartRoutingRealModelNote": "You can still pass a real model ID (e.g. gpt-5.4). Tokfai will not auto-fallback for explicit IDs — you get upstream_model_busy if that model is hot.",
  "dashboard.models.smartRoutingTitle": "Alias / Smart routing",
  "dashboard.models.starterTemplateAutoCheap": "auto-cheap → Ecommerce batch starter",
  "dashboard.models.starterTemplateAutoFast": "auto-fast → Chat starter template",
  "dashboard.models.starterTemplateAutoPro": "auto-pro → Quality Chat starter",
  "dashboard.models.starterTemplateHint": "Use this model in a starter template:",
  "dashboard.models.starterTemplateImage": "gpt-image-2 → Image starter template",
  "dashboard.models.startFromModelAutoCheap": "auto-cheap — high-volume ecommerce copy",
  "dashboard.models.startFromModelAutoFast": "auto-fast — first test",
  "dashboard.models.startFromModelAutoPro": "auto-pro — quality workloads",
  "dashboard.models.startFromModelTitle": "Start integration from this model",
  "dashboard.models.statusAvailable": "Available",
  "dashboard.models.statusComingSoon": "Coming soon",
  "dashboard.models.statusPaused": "Paused",
  "dashboard.models.subtitle": "Browse available Tokfai models, capabilities, recommended use cases, and billing notes.",
  "dashboard.models.tableDesc": "Model IDs for API requests and Playgrounds.",
  "dashboard.models.tableTitle": "Model list",
  "dashboard.models.title": "Models",
  "dashboard.models.usageTipsTitle": "Usage tips",
  "dashboard.models.verificationUnavailableNote": "If live verification is temporarily unavailable, choose your model plan now and verify later from Integration Workbench.",
  "dashboard.models.viewCreditsLedger": "View Credits ledger",
  "dashboard.overview.continueDesc": "Pick up testing, review usage, or check your balance.",
  "dashboard.overview.continueTitle": "Continue where you left off",
  "dashboard.overview.manageApiKeys": "Manage API keys",
  "dashboard.overview.onboardingAllComplete": "Setup complete — you're ready to build.",
  "dashboard.overview.recentActivityDesc": "Your five most recent API requests.",
  "dashboard.overview.recentActivityEmpty": "No API calls yet. Run a Playground test and your latest requests will appear here.",
  "dashboard.overview.recentActivityTitle": "Recent activity",
  "dashboard.overview.recentActivityViewCredits": "View Credits",
  "dashboard.overview.recentActivityViewUsage": "View Usage",
  "dashboard.overview.securityTitle": "Security reminders",
  "dashboard.overview.stateNeedsFirstCallPlayground": "Chat Playground",
  "dashboard.overview.stateNeedsFirstCallQuickstart": "View integration docs",
  "dashboard.overview.stepCompleted": "Completed",
  "dashboard.overview.stepCurrent": "Current",
  "dashboard.overview.stepNext": "Next",
  "dashboard.overview.title": "Overview",
  "dashboard.overview.viewAllUsage": "View all usage",
  "dashboard.playground.apiKey": "API key",
  "dashboard.playground.apiKeyLoadTimedOut": "Timed out loading the selected API key. Paste the full secret or try again.",
  "dashboard.playground.copied": "Copied",
  "dashboard.playground.copyRequestId": "Copy request_id",
  "dashboard.playground.copySecret": "Copy secret",
  "dashboard.playground.costHint": "Playground calls consume credits. Check your balance first. Actual charges are recorded in the credits ledger.",
  "dashboard.playground.createdAt": "created_at",
  "dashboard.playground.createTestKey": "Create test key",
  "dashboard.playground.creatingTestKey": "Creating…",
  "dashboard.playground.creditsCharged": "credits charged",
  "dashboard.playground.currentKeySelection": "Current selection: {name} ({prefix}…)",
  "dashboard.playground.errors.invalidToken": "API key is invalid or revoked. Create a new key.",
  "dashboard.playground.errors.keyNotRetrievable": "For security, full keys aren't stored long-term. Paste your key or create a new test key.",
  "dashboard.playground.errors.missingPrompt": "Please enter a prompt.",
  "dashboard.playground.errors.missingToken": "Missing API key. Create and paste an active key first.",
  "dashboard.playground.errors.unknown": "Request failed. Please try again later.",
  "dashboard.playground.errors.upstreamError": "The selected model is temporarily unavailable or under high load.",
  "dashboard.playground.forImageModels": "For image models, use",
  "dashboard.playground.fullApiKey": "Full API key",
  "dashboard.playground.goToApiKeys": "Go to API Keys",
  "dashboard.playground.hideKey": "Hide",
  "dashboard.playground.inputTokens": "input tokens",
  "dashboard.playground.manageApiKeys": "Manage API Keys",
  "dashboard.playground.manageApiKeysHint": "To revoke or delete keys, go to the API Keys page.",
  "dashboard.playground.model": "Model",
  "dashboard.playground.noKeyBody": "Create a test key to run your first real Playground call.",
  "dashboard.playground.noKeyTitle": "No active API Key yet",
  "dashboard.playground.outputTokens": "output tokens",
  "dashboard.playground.pasteKey": "Paste key",
  "dashboard.playground.pasteKeySecurityHint": "The key is kept in this page only and is not saved. Do not use on shared devices.",
  "dashboard.playground.pasteOtherKey": "Paste another key",
  "dashboard.playground.productionKeyHint": "For production, create and copy your sk-tokfai key on the API Keys page.",
  "dashboard.playground.prompt": "Prompt",
  "dashboard.playground.promptPlaceholder": "Enter test content, e.g. introduce Tokfai API in one sentence.",
  "dashboard.playground.request": "Test request",
  "dashboard.playground.requestDesc": "Select or create an API key, pick a chat model, and send one non-streaming message.",
  "dashboard.playground.requestedModel": "Requested model",
  "dashboard.playground.requestId": "request_id",
  "dashboard.playground.requestStatus": "Status",
  "dashboard.playground.resolvedModel": "Resolved model",
  "dashboard.playground.responseContent": "Response",
  "dashboard.playground.responsePlaceholder": "The model response will appear here after you send.",
  "dashboard.playground.resultTitle": "Result",
  "dashboard.playground.run": "Send test",
  "dashboard.playground.running": "Sending…",
  "dashboard.playground.secretNotStored": "The full secret is loaded only for this request and is not stored in the browser.",
  "dashboard.playground.secretOnceHint": "Full secret is shown only once at creation. After refresh it cannot be viewed again — create a new key if lost.",
  "dashboard.playground.selectKey": "Select key",
  "dashboard.playground.showKey": "Show",
  "dashboard.playground.statusFailed": "Failed",
  "dashboard.playground.statusSuccess": "Success",
  "dashboard.playground.subtitle": "Choose a model, send a test request, and verify the Tokfai API works.",
  "dashboard.playground.successBalanceHint": "Recorded in",
  "dashboard.playground.successReconcileHint": "Copy request_id and search it in Usage and Credits to reconcile this call.",
  "dashboard.playground.testKeyCreated": "Test key created. Copy the full secret — it won't be shown again after refresh.",
  "dashboard.playground.testNow": "Test now",
  "dashboard.playground.title": "Playground",
  "dashboard.playground.tokensNotReturned": "—",
  "dashboard.playground.totalTokens": "total tokens",
  "dashboard.playground.usageFallback": "Usage for this call is recorded in the credits ledger at /dashboard/credits.",
  "dashboard.playground.viewChatApiDocs": "Chat API docs",
  "dashboard.playground.viewCredits": "View Credits",
  "dashboard.playground.viewCreditsLedger": "View credits ledger",
  "dashboard.playground.viewDocs": "View docs",
  "dashboard.playground.viewModels": "View models",
  "dashboard.playground.viewOpenAiSdkDocs": "OpenAI SDK docs",
  "dashboard.playground.viewUsage": "View Usage",
  "dashboard.playground.waitingForModel": "Waiting for the model…",
  "dashboard.shell.lowCredits": "Low credits",
  "dashboard.shell.productTagline": "OpenAI-compatible API gateway",
  "dashboard.shell.sidebarCreditsLabel": "Credits balance",
  "dashboard.shell.topUp": "Top up",
  "dashboard.usage.colCompletion": "Completion",
  "dashboard.usage.colCredits": "Credits charged",
  "dashboard.usage.colModel": "Model",
  "dashboard.usage.colPrompt": "Prompt",
  "dashboard.usage.colRequestId": "Request ID",
  "dashboard.usage.colRequestIdHint": "Use when contacting support to trace a request",
  "dashboard.usage.colRoute": "Route",
  "dashboard.usage.colStatus": "Status",
  "dashboard.usage.colTotal": "Total",
  "dashboard.usage.colWhen": "When",
  "dashboard.usage.copiedRequestId": "Copied",
  "dashboard.usage.copyRequestId": "Copy request ID",
  "dashboard.usage.emptyHint": "Send a test from Chat Playground or Image Playground to generate your first usage log.",
  "dashboard.usage.emptyTitle": "No usage records yet.",
  "dashboard.usage.emptyViewCredits": "View credits ledger",
  "dashboard.usage.howItWorksItem1": "Each row is one API request with model, route, status, tokens, credits charged, and request_id.",
  "dashboard.usage.howItWorksItem2": "Chat rows show prompt, completion, and total tokens. Image rows show credits per generation.",
  "dashboard.usage.howItWorksItem3": "Balance and totals on Credits match this page — Usage and Credits are the source of truth.",
  "dashboard.usage.howItWorksItem4": "Failed requests are listed here but are not charged.",
  "dashboard.usage.howItWorksItem5": "Failed requests help with troubleshooting and are usually not charged; successful requests record tokens and credits_charged.",
  "dashboard.usage.howItWorksTitle": "Reading this page",
  "dashboard.usage.imageGeneration": "image generation",
  "dashboard.usage.integrationWorkbenchLink": "Integration Workbench — reconcile request_id",
  "dashboard.usage.loadError": "Could not load usage",
  "dashboard.usage.loadErrorDesc": "Usage logs could not be loaded right now. Please try again later.",
  "dashboard.usage.loadingRecentRequests": "Recent requests",
  "dashboard.usage.loadingRecentRequestsDesc": "Loading the latest usage logs.",
  "dashboard.usage.recentRequests": "Recent requests",
  "dashboard.usage.recentRequestsDesc": "Last 50 entries, newest first. Run a request in the Chat Playground or Image Playground to generate more.",
  "dashboard.usage.statCredits7d": "Credits used (7d)",
  "dashboard.usage.statRequests24h": "Requests (24h)",
  "dashboard.usage.statRequests7d": "Requests (7d)",
  "dashboard.usage.statTokens7d": "Tokens (7d)",
  "dashboard.usage.subtitle": "Review API requests, models, status, token counts, and credits charged for your account.",
  "dashboard.usage.title": "Usage",
  "integration.apiKeyBulletAuthHeader": "Header format is always Authorization: Bearer sk-tokfai_xxx (replace xxx with your secret).",
  "integration.apiKeyBulletOneKeyAllApis": "One API Key works for Chat API, Image API, and Batch API — you do not need a separate key per model.",
  "integration.apiKeyBulletOneTime": "The full secret is shown once when you create a key — copy it immediately.",
  "integration.apiKeyBulletReveal": "Active keys can be copied again from API Keys via Copy key (reveal).",
  "integration.apiKeyBulletRevoke": "If a key is leaked, Revoke it immediately and create a new key.",
  "integration.apiKeyBulletServerSide": "Store keys on servers, scripts, IDE, or gateway configs only — never in public frontends or public source code.",
  "integration.apiKeyCopyNowTitle": "You can copy now",
  "integration.apiReadiness.apiKeysHint": "If live verification is unavailable, keep this key safe and continue with the Integration Workbench.",
  "integration.linkCredits": "Open Credits",
  "integration.nav500OnlineReadiness": "500 online readiness",
  "integration.navCapacityPlanner": "Capacity planner",
  "integration.navRetryBackoff": "Retry & backoff",
  "integration.navTrafficGovernor": "Traffic governor",
  "integration.oneLineCurlPasteAnywhere": "Paste in any terminal. No install. No project folder required.",
  "integration.starterTemplates.openLibrary": "Open Starter Templates",
  "integration.trafficGovernor.scaleSafelyTitle": "Scale safely",
  "integration.troubleshooting.curlFailsTitle": "If the curl fails",
  "integration.troubleshooting.invalidTokenGuide": "invalid_token guide",
  "integration.troubleshooting.missingTokenGuide": "missing_token guide",
  "integration.troubleshooting.openTroubleshooting": "Open troubleshooting",
  "nav.dashboard": "Dashboard",
  "quickstart.copied": "Copied",
  "quickstart.copy": "Copy",
};

export const ZH: Record<string, string> = {
  "admin.adjust.addCredits": "增加积分",
  "admin.adjust.amount": "金额",
  "admin.adjust.deductCredits": "扣减积分",
  "admin.adjust.direction": "方向",
  "admin.adjust.directionAdd": "增加",
  "admin.adjust.directionDeduct": "扣减",
  "admin.adjust.email": "邮箱",
  "admin.adjust.invalidAmount": "请输入大于 0 的金额。",
  "admin.adjust.missingReason": "请填写调账原因。",
  "admin.adjust.reason": "原因",
  "admin.adjust.reasonPlaceholder": "填写本次调账原因",
  "admin.adjust.submit": "提交调账",
  "admin.adjust.submitting": "提交中…",
  "admin.adjust.subtitle": "通过 DMIT /admin/credits/adjust 进行管理员手动调账。",
  "admin.adjust.success": "调账成功。新余额：{balance}（变动 {delta}）。",
  "admin.adjust.title": "积分调账",
  "admin.adjust.userId": "目标 user_id",
  "admin.announcements.formDesc": "数字越小排序越靠前。可见时间留空表示始终可见。",
  "admin.announcements.loadFailed": "加载公告失败。",
  "admin.announcements.requiredFields": "标题与正文为必填项。",
  "admin.announcements.saveFailed": "保存公告失败。",
  "admin.announcements.subtitle": "创建与管理控制台公告。",
  "admin.common.accessDenied": "无 Admin 权限",
  "admin.common.adminTools": "Admin 工具",
  "admin.common.adminVerifyFailed": "无法验证 Admin 访问权限。",
  "admin.common.comingSoon": "即将开放",
  "admin.common.notAuthorized": "当前账户未授权访问 Admin。",
  "admin.common.readOnlyPhase": "本阶段只读",
  "admin.common.refresh": "刷新",
  "admin.common.refreshing": "刷新中…",
  "admin.common.retry": "重试",
  "admin.common.sessionExpired": "登录状态失效，请重新登录",
  "admin.common.sessionExpiredTitle": "登录已失效",
  "admin.common.signInAgain": "重新登录",
  "admin.common.unknown": "未知",
  "admin.common.verifyingAccess": "正在验证 Admin 权限",
  "admin.common.verifyingAccessDesc": "正在向 Admin API 确认当前登录状态…",
  "admin.credits.adjustmentStats": "调账",
  "admin.credits.basedOnLoadedBatch": "仅统计已加载批次",
  "admin.credits.colAmount": "金额",
  "admin.credits.colBalanceAfter": "变更后余额",
  "admin.credits.colCreated": "时间",
  "admin.credits.colReason": "原因",
  "admin.credits.colReference": "Reference",
  "admin.credits.colType": "类型",
  "admin.credits.currentBalance": "当前余额",
  "admin.credits.debitStats": "扣费",
  "admin.credits.email": "邮箱",
  "admin.credits.entryCount": "{count} 条",
  "admin.credits.groupStatsDesc": "基于该账户已加载的最近 50 条账本条目分组汇总。",
  "admin.credits.groupStatsTitle": "账本分组统计",
  "admin.credits.lastUpdated": "最后更新",
  "admin.credits.ledgerEntries": "账本条目",
  "admin.credits.ledgerEntriesDesc": "只读视图：{email}。",
  "admin.credits.noLedgerEntries": "该用户暂无账本记录。",
  "admin.credits.noRecentDebits": "已加载批次中暂无扣费记录。",
  "admin.credits.noRecentTopups": "已加载批次中暂无充值记录。",
  "admin.credits.reasonAdminAdjustment": "管理员调账",
  "admin.credits.reasonChatUsage": "API 调用扣费",
  "admin.credits.reasonStripeTopUp": "Stripe 充值到账",
  "admin.credits.reasonSystemFix": "系统修正",
  "admin.credits.recentDebits": "最近扣费记录",
  "admin.credits.recentDebitsDesc": "已加载批次中的最近扣费条目。",
  "admin.credits.recentTopups": "最近充值记录",
  "admin.credits.recentTopupsDesc": "已加载批次中的最近入账条目。",
  "admin.credits.refresh": "刷新",
  "admin.credits.refreshing": "刷新中…",
  "admin.credits.topupStats": "充值 / 入账",
  "admin.credits.totalUsed": "累计使用",
  "admin.credits.viewUsageLogs": "查看用量日志",
  "admin.debug.adminError": "Admin 错误",
  "admin.debug.apiBaseUrl": "API Base URL",
  "admin.debug.currentUserEmail": "当前用户邮箱",
  "admin.debug.errorMessage": "错误信息",
  "admin.debug.hasSessionToken": "是否有 session token",
  "admin.debug.statusCode": "状态码",
  "admin.models.emptyFilters": "没有符合当前筛选条件的模型。",
  "admin.models.filterAllStatuses": "全部状态",
  "admin.models.filterAllTypes": "全部类型",
  "admin.models.filterStatus": "状态",
  "admin.models.filterType": "类型",
  "admin.models.manage.addModel": "新增模型",
  "admin.models.manage.archive": "下架",
  "admin.models.manage.billingChat": "chat",
  "admin.models.manage.billingImage": "image",
  "admin.models.manage.cancel": "取消",
  "admin.models.manage.createModel": "创建模型",
  "admin.models.manage.createTitle": "新增模型",
  "admin.models.manage.edit": "编辑",
  "admin.models.manage.editTitle": "编辑模型",
  "admin.models.manage.formBillingType": "计费类型",
  "admin.models.manage.formDisplayName": "展示名称",
  "admin.models.manage.formEnabled": "模型启用",
  "admin.models.manage.formId": "Model ID",
  "admin.models.manage.formImageCredits": "Credits / 次",
  "admin.models.manage.formInputPerMillion": "Input credits / 100万 tokens",
  "admin.models.manage.formMarkupRatio": "Markup 比例（可选）",
  "admin.models.manage.formOutputPerMillion": "Output credits / 100万 tokens",
  "admin.models.manage.formPricingEnabled": "定价启用",
  "admin.models.manage.formPricingPreviewOnlyNotice": "该模型或其定价尚未完全启用。下方数值仅供后台预览，用户尚不可调用或购买。",
  "admin.models.manage.formPricingVisible": "定价在 Dashboard 展示",
  "admin.models.manage.formProvider": "Provider",
  "admin.models.manage.formSortOrder": "排序",
  "admin.models.manage.formType": "类型",
  "admin.models.manage.formUpstreamNote": "上游成本备注（仅 Admin）",
  "admin.models.manage.formUpstreamNoteHint": "内部备注，不对用户展示",
  "admin.models.manage.formVideoUnavailableNotice": "视频模型尚未启用。按次积分与人民币示例仅供参考，不代表已对用户开放。",
  "admin.models.manage.formVisible": "模型前台可见",
  "admin.models.manage.loadFailed": "加载模型失败。",
  "admin.models.manage.loadFailedTitle": "无法加载模型",
  "admin.models.manage.loading": "加载模型中…",
  "admin.models.manage.pricePreviewDisclaimer": "人民币价格仅为充值积分套餐折算示例，实际以用户充值套餐和最终扣费记录为准。",
  "admin.models.manage.restore": "恢复",
  "admin.models.manage.saveChanges": "保存修改",
  "admin.models.manage.saving": "保存中…",
  "admin.models.manage.statusArchived": "已归档",
  "admin.models.manage.statusDisabled": "已禁用",
  "admin.models.manage.subtitle": "通过 DMIT 管理目录模型与定价。扣费仍走现有 usage / credits 主链路。",
  "admin.models.manage.syncCatalog": "同步缺失模型",
  "admin.models.manage.syncing": "同步中…",
  "admin.models.manage.syncSuccess": "目录同步完成：新增 {models} 个模型、{pricing} 条定价；跳过 {skipped} 个已存在项。",
  "admin.models.manage.tableBilling": "计费类型",
  "admin.models.manage.tableDesc": "来自 DMIT 的 {count} 个模型。",
  "admin.models.manage.tablePricePreview": "价格示例",
  "admin.models.manage.tablePricing": "定价",
  "admin.models.manage.tableTitle": "模型列表",
  "admin.models.manage.tableUpdated": "更新时间",
  "admin.models.manage.title": "模型管理",
  "admin.models.manage.typeOther": "其他",
  "admin.models.searchFilters": "搜索与筛选",
  "admin.models.searchLabel": "搜索模型名称或 Model ID",
  "admin.models.searchPlaceholder": "例如 gemini-3.1-pro",
  "admin.models.statusAvailable": "可用",
  "admin.models.statusComingSoon": "即将上线",
  "admin.models.subtitle": "管理目录模型与定价。实际扣费仍记录在 Usage 与 Credits 中。",
  "admin.models.tableModelId": "Model ID",
  "admin.models.tableModelName": "模型名称",
  "admin.models.tableStatus": "状态",
  "admin.models.tableType": "类型",
  "admin.models.title": "模型与定价",
  "admin.models.typeChat": "对话",
  "admin.models.typeImage": "图像",
  "admin.models.typeVideo": "视频",
  "admin.nav.backToDashboard": "返回控制台",
  "admin.nav.sections": "Admin 导航",
  "admin.rechargePlans.archive": "归档",
  "admin.rechargePlans.archived": "套餐已归档。",
  "admin.rechargePlans.archivedBadge": "已归档",
  "admin.rechargePlans.cancel": "取消",
  "admin.rechargePlans.checkoutHint": "Checkout 与 webhook 仅按 credits 列入账。",
  "admin.rechargePlans.colActions": "操作",
  "admin.rechargePlans.colAmount": "售价",
  "admin.rechargePlans.colArchived": "归档",
  "admin.rechargePlans.colBadge": "角标",
  "admin.rechargePlans.colBaseCredits": "基础积分",
  "admin.rechargePlans.colBonusCredits": "赠送积分",
  "admin.rechargePlans.colCredits": "到账积分",
  "admin.rechargePlans.colDescription": "描述",
  "admin.rechargePlans.colEnabled": "允许 Checkout",
  "admin.rechargePlans.colId": "ID",
  "admin.rechargePlans.colName": "名称",
  "admin.rechargePlans.colSortOrder": "排序",
  "admin.rechargePlans.colStripePriceId": "Stripe Price ID",
  "admin.rechargePlans.colUpdated": "更新时间",
  "admin.rechargePlans.colVisible": "用户端展示",
  "admin.rechargePlans.create": "创建",
  "admin.rechargePlans.created": "充值套餐已创建。",
  "admin.rechargePlans.createFailed": "创建充值套餐失败。",
  "admin.rechargePlans.createPlan": "新建套餐",
  "admin.rechargePlans.createTitle": "新建充值套餐",
  "admin.rechargePlans.creating": "创建中…",
  "admin.rechargePlans.creditsComputedHint": "到账积分（credits）只读，等于基础积分 + 赠送积分。",
  "admin.rechargePlans.disableCheckout": "禁用 Checkout",
  "admin.rechargePlans.duplicate": "复制",
  "admin.rechargePlans.duplicated": "已复制为新套餐 {id}。",
  "admin.rechargePlans.edit": "编辑",
  "admin.rechargePlans.empty": "暂无充值套餐。",
  "admin.rechargePlans.enableCheckout": "启用 Checkout",
  "admin.rechargePlans.hideFromPricing": "从定价页隐藏",
  "admin.rechargePlans.loadFailed": "加载充值套餐失败。",
  "admin.rechargePlans.no": "否",
  "admin.rechargePlans.restored": "套餐已恢复。",
  "admin.rechargePlans.save": "保存",
  "admin.rechargePlans.saved": "充值套餐已保存。",
  "admin.rechargePlans.saveFailed": "保存充值套餐失败。",
  "admin.rechargePlans.saving": "保存中…",
  "admin.rechargePlans.showArchived": "显示已归档",
  "admin.rechargePlans.showOnPricing": "在定价页展示",
  "admin.rechargePlans.subtitle": "创建与管理充值套餐。到账积分由服务端按「基础 + 赠送」自动计算。",
  "admin.rechargePlans.tableDesc": "保存后影响定价页与充值 Checkout；Checkout 仍只传 plan_id。",
  "admin.rechargePlans.tableTitle": "套餐列表",
  "admin.rechargePlans.title": "充值套餐",
  "admin.rechargePlans.unarchive": "取消归档",
  "admin.rechargePlans.yes": "是",
  "admin.usage.colCompletion": "Completion",
  "admin.usage.colCreated": "时间",
  "admin.usage.colCredits": "扣除积分",
  "admin.usage.colEmail": "邮箱",
  "admin.usage.colModel": "Model",
  "admin.usage.colPrompt": "Prompt",
  "admin.usage.colRequestId": "请求 ID",
  "admin.usage.colStatus": "状态",
  "admin.usage.colTotal": "Total",
  "admin.usage.empty": "暂无用量记录。",
  "admin.users.actions": "操作",
  "admin.users.createdAt": "注册时间",
  "admin.users.creditsBalance": "积分余额",
  "admin.users.email": "邮箱",
  "admin.users.hideDetails": "收起详情",
  "admin.users.ledger": "账本",
  "admin.users.noUsers": "未找到用户资料。",
  "admin.users.subtitle": "账户概览，含余额、累计充值、累计消耗与人工调账入口。",
  "admin.users.title": "用户管理",
  "admin.users.totalCreditsPurchased": "累计充值",
  "admin.users.totalCreditsUsed": "累计消耗",
  "admin.users.updatedAt": "更新时间",
  "admin.users.userDetailTitle": "账户详情",
  "admin.users.userManagement": "用户管理",
  "admin.users.userManagementDesc": "浏览邮箱、user_id、积分余额、累计充值与累计消耗。可通过「增加积分 / 扣减积分」进行人工调账。",
  "admin.users.userProfiles": "用户资料",
  "admin.users.userProfilesDesc": "来自 admin users 接口的 {count} 个账户。",
  "admin.users.viewDetails": "查看详情",
  "admin.users.viewRecentLedger": "查看账本",
  "admin.users.viewRecentUsage": "查看最近用量",
  "auth.success.accountCreated": "账号已创建，可以开始使用了。",
  "auth.success.dismiss": "关闭",
  "auth.success.welcomeBack": "登录成功，欢迎回来！",
  "common.chatPlayground": "Chat Playground",
  "common.footerTagline": "Tokfai · OpenAI 兼容的图像与对话 API",
  "common.imagePlayground": "Image Playground",
  "common.open": "打开",
  "common.signedInAs": "已登录",
  "common.signingOut": "正在退出…",
  "common.signOut": "退出登录",
  "common.unavailable": "不可用",
  "dashboard.announcements.announcementContent": "正文",
  "dashboard.announcements.announcements": "公告",
  "dashboard.announcements.announcementSaved": "公告已保存。",
  "dashboard.announcements.announcementTitle": "标题",
  "dashboard.announcements.announcementType": "类型",
  "dashboard.announcements.editAnnouncement": "编辑公告",
  "dashboard.announcements.enabled": "启用",
  "dashboard.announcements.latestAnnouncements": "最新公告",
  "dashboard.announcements.newAnnouncement": "新建公告",
  "dashboard.announcements.noAnnouncements": "暂无公告。",
  "dashboard.announcements.pinned": "置顶",
  "dashboard.announcements.subtitle": "系统通知、维护窗口与使用说明。",
  "dashboard.announcements.viewAll": "查看全部",
  "dashboard.announcements.visibleFrom": "可见开始时间",
  "dashboard.announcements.visibleUntil": "可见结束时间",
  "dashboard.apiKeys.active": "活跃",
  "dashboard.apiKeys.apiKeyCreated": "API 密钥已创建",
  "dashboard.apiKeys.apiKeyCreatedNamed": "API 密钥已创建：{name}",
  "dashboard.apiKeys.apiKeyUnderstandingDesc": "调用 Tokfai API 的凭证——规则与文档 API Key 章节一致。",
  "dashboard.apiKeys.apiKeyUnderstandingTitle": "什么是 Tokfai API Key？",
  "dashboard.apiKeys.authHeaderHint": "在请求中使用",
  "dashboard.apiKeys.buildPayload": "生成 payload",
  "dashboard.apiKeys.buildStarterTemplate": "生成接入模板",
  "dashboard.apiKeys.capacityRateLimitsLink": "容量与限流",
  "dashboard.apiKeys.cherryStudioGuide": "Cherry Studio 接入指南",
  "dashboard.apiKeys.colActions": "操作",
  "dashboard.apiKeys.colCreated": "创建时间",
  "dashboard.apiKeys.colLastUsed": "最近使用",
  "dashboard.apiKeys.colName": "名称",
  "dashboard.apiKeys.colPrefix": "Prefix",
  "dashboard.apiKeys.colRevokedAt": "撤销时间",
  "dashboard.apiKeys.colStatus": "状态",
  "dashboard.apiKeys.commercialFaqGuide": "商业 FAQ",
  "dashboard.apiKeys.copied": "已复制",
  "dashboard.apiKeys.copyAuthHeader": "复制 Authorization header",
  "dashboard.apiKeys.copyCherryConfig": "复制 Cherry 配置",
  "dashboard.apiKeys.copyCursorConfig": "复制 Cursor 配置",
  "dashboard.apiKeys.copyFullKey": "复制完整密钥",
  "dashboard.apiKeys.copying": "复制中…",
  "dashboard.apiKeys.copyKey": "复制密钥",
  "dashboard.apiKeys.copyNodeSdkConfig": "复制 Node.js SDK 配置",
  "dashboard.apiKeys.copyOneLineChatCurl": "复制单行 Chat curl",
  "dashboard.apiKeys.copyOneLineModelsCurl": "复制单行 Models curl",
  "dashboard.apiKeys.copyPowerShellChatCurl": "复制 PowerShell Chat curl",
  "dashboard.apiKeys.copyPythonSdkConfig": "复制 Python SDK 配置",
  "dashboard.apiKeys.createApiKey": "创建 API 密钥",
  "dashboard.apiKeys.createApiKeyDesc": "可选名称，便于区分。留空则使用默认名称。",
  "dashboard.apiKeys.creating": "创建中…",
  "dashboard.apiKeys.cursorGuide": "Cursor 接入指南",
  "dashboard.apiKeys.emptyCreateFirst": "创建第一个 API Key",
  "dashboard.apiKeys.emptyRecharge": "去充值积分",
  "dashboard.apiKeys.emptyTitle": "还没有 API 密钥。创建第一把密钥即可开始测试——完整 secret 仅展示一次，请立即复制。",
  "dashboard.apiKeys.errorCode": "错误码",
  "dashboard.apiKeys.errorHttpStatus": "HTTP 状态",
  "dashboard.apiKeys.errorRequestId": "request_id",
  "dashboard.apiKeys.goToCredits": "前往 Credits",
  "dashboard.apiKeys.goToUsage": "前往 Usage",
  "dashboard.apiKeys.integrationLinksTitle": "体验与核对",
  "dashboard.apiKeys.integrationWorkbench": "接入工作台",
  "dashboard.apiKeys.keyName": "密钥名称",
  "dashboard.apiKeys.keyNamePlaceholder": "例如 production",
  "dashboard.apiKeys.keyReadyMessage": "密钥已就绪。请先验证一次请求，再规划容量并完成接入交接。",
  "dashboard.apiKeys.largeVolumeBatchGuide": "大批量 Batch 指南",
  "dashboard.apiKeys.largeVolumeIntegrationLink": "大批量接入",
  "dashboard.apiKeys.listUnavailableDesc": "密钥列表无法加载 — API 可能暂时不可用。你仍可在下方创建新密钥，或几分钟后重试。",
  "dashboard.apiKeys.listUnavailableTitle": "无法加载 API 密钥列表",
  "dashboard.apiKeys.loadError": "无法加载 API 密钥",
  "dashboard.apiKeys.loadErrorAuthDesc": "登录状态异常，请重新登录。",
  "dashboard.apiKeys.loadErrorTempDesc": "无法加载 API 密钥，请稍后重试。",
  "dashboard.apiKeys.neverUsed": "从未使用",
  "dashboard.apiKeys.nextStepBatch": "Batch API 见文档 Batch 章节。",
  "dashboard.apiKeys.nextStepCherry": "Cherry Studio 配置见文档 Cherry 章节。",
  "dashboard.apiKeys.nextStepCurl": "复制单行 models curl 验证鉴权，或单行 chat curl 做完整测试（与文档 API Key 章节一致）。",
  "dashboard.apiKeys.nextStepCursor": "Cursor 配置见文档 Cursor 章节。",
  "dashboard.apiKeys.nextStepSdk": "更多接入方式见文档：OpenAI SDK、Cursor、Cherry Studio。",
  "dashboard.apiKeys.nextStepsTitle": "通过 Tokfai API 接入",
  "dashboard.apiKeys.oneTimeSecretDesc": "请立即复制并妥善保存——完整密钥仅在创建时展示一次。",
  "dashboard.apiKeys.online500Guide": "500 人在线指南",
  "dashboard.apiKeys.openStarterTemplates": "打开接入模板库",
  "dashboard.apiKeys.pasteTerminalNote": "在任意终端粘贴运行。无需仓库、无需安装、无需 cd。",
  "dashboard.apiKeys.productionHandoffTitle": "生产交付",
  "dashboard.apiKeys.productionUseGuide": "生产上线",
  "dashboard.apiKeys.quickStartDocs": "快速上手指南",
  "dashboard.apiKeys.retryBackoffGuide": "重试与退避指南",
  "dashboard.apiKeys.retryRateLimitGuide": "重试与限流指南",
  "dashboard.apiKeys.revoke": "吊销",
  "dashboard.apiKeys.revokeConfirm": "确定吊销此 API 密钥？使用该密钥的应用将无法继续工作，且无法恢复。",
  "dashboard.apiKeys.revoked": "已吊销",
  "dashboard.apiKeys.revoking": "吊销中…",
  "dashboard.apiKeys.savedMyKey": "我已保存密钥",
  "dashboard.apiKeys.securityDesc": "请将 API Key 视为密码，不要暴露在客户端代码或公开源码中。",
  "dashboard.apiKeys.securityItem1": "API Key 只应保存在服务端——不要写入移动应用、浏览器或公开前端。",
  "dashboard.apiKeys.securityItem2": "若密钥泄露或误提交到 git，请立即 Revoke 并创建新密钥。",
  "dashboard.apiKeys.securityItem3": "完整 secret 仅在创建时完整展示；之后可通过活跃密钥的「复制密钥」再次复制完整 secret。",
  "dashboard.apiKeys.securityItem4": "一把 API Key 可用于 Chat、Image、Batch——无需为每个模型单独创建密钥。",
  "dashboard.apiKeys.securityItem5": "若密钥泄露或误提交，请立即 Revoke 并创建新密钥。",
  "dashboard.apiKeys.securityTitle": "保护你的密钥",
  "dashboard.apiKeys.sessionKeyDocsNote": "点击「我已保存密钥」后，本浏览器会话仍会自动填充 Docs 示例。刷新页面会清空 — 若出现占位符请重新复制密钥或单行 curl。",
  "dashboard.apiKeys.startIntegration": "开始接入",
  "dashboard.apiKeys.startIntegrationWorkbench": "打开接入工作台",
  "dashboard.apiKeys.storeBackendSecurityNote": "请将 API Key 保存在后端。禁止在浏览器前端暴露。",
  "dashboard.apiKeys.subtitleCreate": "创建密钥以向 {baseUrl} 发起认证请求。完整密钥仅在创建时展示一次；活跃密钥可通过「复制密钥」再次获取。",
  "dashboard.apiKeys.subtitleMeta": "查看 Tokfai 账户的 API 密钥元数据。",
  "dashboard.apiKeys.title": "API 密钥",
  "dashboard.apiKeys.verifyCredits": "在 Credits 核对",
  "dashboard.apiKeys.verifyUsage": "在 Usage 核对",
  "dashboard.apiKeys.viewApiDocs": "查看 API 文档",
  "dashboard.apiKeys.viewApiKeyDocs": "API Key 文档",
  "dashboard.apiKeys.viewDocs": "查看文档",
  "dashboard.apiKeys.viewUsageCreditsDocs": "Usage / Credits 指南",
  "dashboard.apiKeys.yourApiKey": "你的 API 密钥",
  "dashboard.apiKeys.yourApiKeys": "你的 API 密钥",
  "dashboard.apiKeys.yourApiKeysDesc": "列表展示 prefix 便于识别。活跃密钥可通过「复制密钥」获取完整 secret。",
  "dashboard.credits.actionApiKeys": "查看 API Key",
  "dashboard.credits.actionDocs": "快速接入文档",
  "dashboard.credits.actionRecharge": "充值积分",
  "dashboard.credits.checkoutCancelled": "Checkout 已取消",
  "dashboard.credits.checkoutCancelledDesc": "未增加积分。请前往定价页选择其他套餐。",
  "dashboard.credits.colAmount": "金额",
  "dashboard.credits.colBalanceAfter": "变更后余额",
  "dashboard.credits.colCreated": "时间",
  "dashboard.credits.colPlan": "套餐",
  "dashboard.credits.colReason": "原因",
  "dashboard.credits.colReference": "Reference",
  "dashboard.credits.colSession": "Checkout session",
  "dashboard.credits.colStatus": "状态",
  "dashboard.credits.colType": "类型",
  "dashboard.credits.copiedReference": "已复制",
  "dashboard.credits.copyReference": "复制 reference",
  "dashboard.credits.createApiKey": "创建 API Key",
  "dashboard.credits.currentBalance": "当前 credits 余额",
  "dashboard.credits.emptyLedger": "暂无积分流水。先在定价页充值、创建 API Key，再发起 Playground 测试——充值与扣费记录会显示在此。",
  "dashboard.credits.emptyLedgerTopUp": "去充值积分",
  "dashboard.credits.emptyOrders": "暂无充值订单。",
  "dashboard.credits.howItWorksItem1": "本页余额与累计数据以 Usage 和 Credits 记录为准，是核账来源。",
  "dashboard.credits.howItWorksItem2": "Chat API（POST /v1/chat/completions）按 input / output tokens 扣费。",
  "dashboard.credits.howItWorksItem3": "Image API（POST /v1/images/generations）按每次成功生成扣费。",
  "dashboard.credits.howItWorksItem4": "Playground 与 API 仅在请求成功后才扣费。",
  "dashboard.credits.howItWorksItem5": "失败请求不扣费。",
  "dashboard.credits.howItWorksItem6": "Credits 账本是余额变化准账本；扣费以成功请求记录为准。",
  "dashboard.credits.howItWorksTitle": "Credits 如何工作",
  "dashboard.credits.integrationWorkbenchLink": "接入工作台",
  "dashboard.credits.last7DaysConsumed": "近 7 天消耗 credits",
  "dashboard.credits.lastChange": "最近一次变动",
  "dashboard.credits.loadErrorAuth": "登录状态异常",
  "dashboard.credits.loadErrorAuthDesc": "登录状态异常，请重新登录。",
  "dashboard.credits.loadErrorTemp": "积分暂时无法加载",
  "dashboard.credits.loadErrorTempDesc": "积分暂时无法加载，请稍后重试。",
  "dashboard.credits.noLedgerForReference": "已加载条目中无匹配的 reference。请确认 API 已成功，或核对 request_id 是否完整。",
  "dashboard.credits.noLedgerHint": "暂无积分记录",
  "dashboard.credits.orderExpiredDesc": "该 Checkout 会话已超时未完成。如需充值，请前往定价页重新选择套餐。",
  "dashboard.credits.orderExpiredTitle": "Checkout 未完成",
  "dashboard.credits.orderPaidDesc": "该笔 Checkout 已支付，积分已入账。",
  "dashboard.credits.orderPaidTitle": "充值已完成",
  "dashboard.credits.paymentReceived": "支付成功",
  "dashboard.credits.paymentReceivedDesc": "支付成功。Stripe 确认 checkout 后 credits 会自动入账（通常数秒内）。若余额未更新，请刷新本页。",
  "dashboard.credits.quickActions": "快捷操作",
  "dashboard.credits.reasonAdminAdjustment": "管理员调账",
  "dashboard.credits.reasonChatUsage": "对话 API 扣费",
  "dashboard.credits.reasonImageUsage": "图像生成扣费",
  "dashboard.credits.reasonStripeCheckout": "Stripe 充值到账",
  "dashboard.credits.reasonSystemFix": "系统修正",
  "dashboard.credits.recentLedger": "积分流水",
  "dashboard.credits.recentLedgerDesc": "最近 50 条，按时间倒序。",
  "dashboard.credits.recentOrders": "充值订单摘要",
  "dashboard.credits.recentOrdersDesc": "最近 10 条 Stripe Checkout 订单。超过 24 小时未支付的 pending 显示为「未完成」。",
  "dashboard.credits.referenceFilterOptional": "Reference / request_id（可选）",
  "dashboard.credits.subtitle": "查看当前余额、充值记录和 API 调用消耗流水。",
  "dashboard.credits.title": "积分账本",
  "dashboard.credits.todayConsumed": "今日消耗 credits",
  "dashboard.firstRun.allComplete": "首次接入已完成——密钥、测试调用与用量记录已就绪。",
  "dashboard.firstRun.checkUsage": "查看 Usage",
  "dashboard.firstRun.cherryGuide": "查看 Cherry Studio 指南",
  "dashboard.firstRun.createApiKey": "创建 API Key",
  "dashboard.firstRun.cursorGuide": "查看 Cursor 指南",
  "dashboard.firstRun.desc": "创建 API Key → 复制单行 curl → 任意终端粘贴运行 → 在 Usage / Credits 对账。",
  "dashboard.firstRun.integrationWorkbench": "接入工作台",
  "dashboard.firstRun.quickStart": "Quick Start curl",
  "dashboard.firstRun.title": "约 3 分钟完成首次接入",
  "dashboard.firstRun.tryPlayground": "打开 Chat Playground",
  "dashboard.firstRun.viewIntegrationDocs": "查看接入文档",
  "dashboard.imagePlayground.addImageUrl": "添加 URL",
  "dashboard.imagePlayground.base64OnlyHint": "API 返回了 base64 图像数据（data[0].b64_json）。Image Playground 仅预览 URL 响应 — 请直接调用 API 或设置 response_format=url。",
  "dashboard.imagePlayground.copiedRequestId": "已复制",
  "dashboard.imagePlayground.copyApiRequest": "复制 API 请求",
  "dashboard.imagePlayground.copyRequestId": "复制 request_id",
  "dashboard.imagePlayground.createApiKey": "创建 API 密钥",
  "dashboard.imagePlayground.createTestKey": "创建测试 Key",
  "dashboard.imagePlayground.errors.billingNotChargedHint": "失败请求通常不会扣费，以 Usage / Credits 记录为准。",
  "dashboard.imagePlayground.errors.invalidDrop": "请拖入 PNG、JPG 或 WEBP 图片文件。",
  "dashboard.imagePlayground.errors.invalidToken": "API Key 无效或已吊销，请重新创建。",
  "dashboard.imagePlayground.errors.keyNotRetrievable": "出于安全考虑，完整 key 不会长期保存。请粘贴 key，或重新创建一个测试 Key。",
  "dashboard.imagePlayground.errors.missingPrompt": "请输入 prompt。",
  "dashboard.imagePlayground.errors.missingToken": "缺少 API Key，请先创建并选择可用密钥。",
  "dashboard.imagePlayground.errors.pageImageNotFound": "无法从该页面解析可用图片。请换用其他 URL 或直接上传图片。",
  "dashboard.imagePlayground.errors.tooManyImages": "最多允许 {max} 张输入图。",
  "dashboard.imagePlayground.errors.unknown": "请求失败，请稍后重试。",
  "dashboard.imagePlayground.estimatedCost": "预计消耗：{credits} credits",
  "dashboard.imagePlayground.generate": "生成",
  "dashboard.imagePlayground.generating": "生成中…",
  "dashboard.imagePlayground.imageToImage": "图生图",
  "dashboard.imagePlayground.inputImagesDesc": "拖拽、上传或粘贴 URL。最多 {max} 张（PNG、JPG、WEBP）。留空则为文生图。",
  "dashboard.imagePlayground.inputImagesDragHint": "PNG、JPG、WEBP · 单张最大 10 MB",
  "dashboard.imagePlayground.inputImagesDragTitle": "拖拽图片到此处或点击上传",
  "dashboard.imagePlayground.inputImagesTitle": "输入图片",
  "dashboard.imagePlayground.inputImagesUrlPlaceholder": "图片或网页 URL——Tokfai 会尝试自动提取图片",
  "dashboard.imagePlayground.metaCreatedAt": "创建时间",
  "dashboard.imagePlayground.metaModel": "模型",
  "dashboard.imagePlayground.modelComingSoon": "该模型即将上线，暂不能在 Playground 中使用。",
  "dashboard.imagePlayground.preparingImages": "准备输入图…",
  "dashboard.imagePlayground.size": "尺寸",
  "dashboard.imagePlayground.successCreditsCharged": "本次扣费 {credits} credits。",
  "dashboard.imagePlayground.successReconcileHint": "复制 request_id，在 Usage 与 Credits 中搜索以核对本次生成。",
  "dashboard.imagePlayground.textToImage": "文生图",
  "dashboard.imagePlayground.title": "Image Playground",
  "dashboard.imagePlayground.toolbenchApiKeyLabel": "API Key",
  "dashboard.imagePlayground.toolbenchBalanceLabel": "余额",
  "dashboard.imagePlayground.toolbenchBillingNoteShort": "成功生成会扣费，失败通常不扣费。",
  "dashboard.imagePlayground.toolbenchCurrentKeyLine": "当前：{name} · {prefix}…",
  "dashboard.imagePlayground.toolbenchInputTitle": "输入",
  "dashboard.imagePlayground.toolbenchInsufficientCredits": "余额不足——请先充值再生成。",
  "dashboard.imagePlayground.toolbenchManageKeysShort": "管理",
  "dashboard.imagePlayground.toolbenchModelLabel": "模型",
  "dashboard.imagePlayground.toolbenchNoKey": "创建 API Key 后即可从你的账户调用 Image API。",
  "dashboard.imagePlayground.toolbenchOpenIntegrationDocs": "打开接入文档",
  "dashboard.imagePlayground.toolbenchPasteKeyShort": "粘贴密钥",
  "dashboard.imagePlayground.toolbenchResultLoadingHint": "请保持此面板可见，结果将显示在这里。",
  "dashboard.imagePlayground.toolbenchResultLoadingTitle": "生成中…",
  "dashboard.imagePlayground.toolbenchResultPanelTitle": "结果",
  "dashboard.imagePlayground.toolbenchResultPlaceholder": "生成的图片将显示在这里",
  "dashboard.imagePlayground.toolbenchRetry": "重试",
  "dashboard.imagePlayground.toolbenchRunSettings": "调用设置",
  "dashboard.imagePlayground.toolbenchServiceDocs": "服务文档",
  "dashboard.imagePlayground.toolbenchSubtitle": "输入 Prompt → 可选参考图 → 生成。仅成功响应才扣费。",
  "dashboard.imagePlayground.toolbenchViewImageApiDocs": "查看 Image API 文档",
  "dashboard.imagePlayground.topUp": "去充值",
  "dashboard.imagePlayground.viewCredits": "查看 Credits",
  "dashboard.imagePlayground.viewImageApiDocs": "Image API 文档",
  "dashboard.imagePlayground.viewUsage": "查看 Usage",
  "dashboard.imagePlayground.waitingForImages": "等待输入图上传或解析完成…",
  "dashboard.models.buildPayloadAutoCheap": "生成 payload — 电商 Batch",
  "dashboard.models.buildPayloadAutoFast": "生成 payload — 通用/客服 Chat",
  "dashboard.models.buildPayloadAutoPro": "生成 payload — 医院/车企质量",
  "dashboard.models.buildPayloadImage": "生成 payload — 图像",
  "dashboard.models.buildPayloadWithModel": "用此 model 生成 payload",
  "dashboard.models.buildTemplateAutoCheap": "生成模板 — auto-cheap Batch",
  "dashboard.models.buildTemplateAutoFast": "生成模板 — auto-fast Chat",
  "dashboard.models.buildTemplateAutoPro": "生成模板 — auto-pro 质量",
  "dashboard.models.buildTemplateImage": "生成模板 — gpt-image-2 图像",
  "dashboard.models.buildTemplateWithModel": "用此 model 生成模板",
  "dashboard.models.capacityPlannerLink": "容量规划器",
  "dashboard.models.colApproxRmb": "预算参考",
  "dashboard.models.colLongEstimate": "长分析 / 套餐可用量",
  "dashboard.models.colModelId": "模型 ID",
  "dashboard.models.colPackageCredits": "到账 credits",
  "dashboard.models.colPackagePlan": "套餐",
  "dashboard.models.colPackageUsageFit": "适用参考",
  "dashboard.models.colShortEstimate": "短对话 / 每张",
  "dashboard.models.colStatus": "状态",
  "dashboard.models.colType": "类型",
  "dashboard.models.copied": "已复制",
  "dashboard.models.copyCurlWithModel": "复制此模型单行 curl",
  "dashboard.models.copyModelId": "复制 model id",
  "dashboard.models.exampleDesc": "带真实密钥的单行 curl 请从 API Keys 或 Docs Quick Start 复制。下方示例使用占位符。",
  "dashboard.models.exampleTitle": "最小请求示例",
  "dashboard.models.footerActions": "下一步",
  "dashboard.models.footerApiKeys": "创建 API Key",
  "dashboard.models.footerCapacityGuide": "容量与限流",
  "dashboard.models.footerCredits": "查看积分账本",
  "dashboard.models.footerDocs": "查看接入文档",
  "dashboard.models.footerHighTrafficBatch": "高流量 — Batch 与容量",
  "dashboard.models.footerIndustryTemplates": "行业模板",
  "dashboard.models.footerPlayground": "打开 Playground",
  "dashboard.models.footerProductionUse": "生产上线",
  "dashboard.models.footerQuickStart": "Quick Start curl",
  "dashboard.models.footerRateLimits": "限流与大批量",
  "dashboard.models.footerStartIntegration": "开始接入",
  "dashboard.models.footerUsage": "查看 Usage",
  "dashboard.models.goLiveAutoCheapEcommerce": "电商大批量文案使用 auto-cheap",
  "dashboard.models.goLiveAutoFastFirst": "首次测试使用 auto-fast",
  "dashboard.models.goLiveAutoProQuality": "高质量任务使用 auto-pro",
  "dashboard.models.goLiveChooseModelPlan": "在容量规划器中选择模型方案",
  "dashboard.models.goLiveOpenTracker": "打开上线跟踪器",
  "dashboard.models.goLiveReadinessTitle": "上线就绪",
  "dashboard.models.highTrafficBatchGovernor": "高流量：使用 Batch API、流量治理与安全重试。",
  "dashboard.models.highTrafficBatchItems": "Batch：单任务 500–1,000 条 — 异步队列轮询。",
  "dashboard.models.highTrafficBatchNote": "高流量？请用 Batch API 并阅读容量指南以控制并发。",
  "dashboard.models.highTrafficCapacityPlanner": "用容量规划器选择并发、模型与 Batch / Chat 分流。",
  "dashboard.models.highTrafficChatConcurrency": "Chat：每应用 25–50 路受控同步并发。",
  "dashboard.models.highTrafficClientQueue": "使用客户端队列与并发治理；大批量任务走 Batch worker。",
  "dashboard.models.highTrafficImageConcurrency": "Image：5–15 路受控并发（慢速生成）。",
  "dashboard.models.highTrafficIntegrationTitle": "高流量接入",
  "dashboard.models.highTrafficNoInfiniteRetry": "429 / 503 / 504 禁止无限重试 — 限制次数并退避。",
  "dashboard.models.highTrafficOnline500Note": "500 online 不等于 500 路同时打上游 — 请用客户端队列限流。",
  "dashboard.models.highTrafficReconcile": "在 Usage / Credits 用 request_id 对账（账本 reference_id）。",
  "dashboard.models.highTrafficUseBatch": "大批量请用 Batch API，勿用同步 Chat 洪峰。",
  "dashboard.models.howToEstimateTitle": "如何估算调用成本？",
  "dashboard.models.inputPrice": "Input",
  "dashboard.models.listDisclaimer": "模型列表会持续更新。",
  "dashboard.models.openIntegrationWorkbench": "打开接入工作台",
  "dashboard.models.openUsageCreditsGuide": "Usage / Credits 指南",
  "dashboard.models.outputPrice": "Output",
  "dashboard.models.overviewChat": "对话模型",
  "dashboard.models.overviewDefault": "推荐默认模型",
  "dashboard.models.overviewImage": "图像模型",
  "dashboard.models.overviewTotal": "可用模型数",
  "dashboard.models.packageEstimateDesc": "对话参考模型 {model}，图像参考 {imageModel}。以下为适用场景说明，非用量承诺。",
  "dashboard.models.packageEstimateRoughNote": "以下为粗略估算，实际可用量会随模型、输入长度、图片尺寸、重试次数变化。",
  "dashboard.models.packageEstimateTitle": "套餐适用参考",
  "dashboard.models.priceDisclaimer": "预算参考口径：1 元≈1000 credits（1 credit≈¥0.001）。",
  "dashboard.models.priceDisclaimerBudget": "以下仅为预算参考，实际扣费以 Usage / Credits 账本为准。",
  "dashboard.models.priceDisclaimerTitle": "价格估算说明",
  "dashboard.models.productionGuidanceAutoCheap": "auto-cheap — 批量低成本任务。",
  "dashboard.models.productionGuidanceAutoFast": "auto-fast — 默认推荐，适合上线冒烟与普通业务。",
  "dashboard.models.productionGuidanceAutoPro": "auto-pro — 高质量任务。",
  "dashboard.models.productionGuidanceBatchNote": "大批量调用建议结合 Batch API，并在 Usage / Credits 按 request_id 对账。",
  "dashboard.models.productionGuidanceExplicit": "真实模型 ID — 高级客户按需选择。",
  "dashboard.models.productionGuidanceTitle": "生产模型策略",
  "dashboard.models.recommendedStartingModel": "推荐起步模型：auto-fast",
  "dashboard.models.recommendedUseCase": "适合场景",
  "dashboard.models.salesTip": "建议先用小套餐完成接入测试，确认模型、质量和消耗后再放量。",
  "dashboard.models.scaleSafelyTitle": "安全扩容",
  "dashboard.models.smartRoutingDesc": "使用 auto-* 别名作为稳定入口。Tokfai 按顺序尝试上游模型，并在响应中返回实际成功的 model。",
  "dashboard.models.smartRoutingRealModelNote": "仍可传入真实 model ID（如 gpt-5.4）。明确指定时 Tokfai 不会自动 fallback — 若该模型繁忙将返回 upstream_model_busy。",
  "dashboard.models.smartRoutingTitle": "别名 / 智能路由",
  "dashboard.models.starterTemplateAutoCheap": "auto-cheap → 电商 Batch 模板",
  "dashboard.models.starterTemplateAutoFast": "auto-fast → Chat 起步模板",
  "dashboard.models.starterTemplateAutoPro": "auto-pro → 高质量 Chat 模板",
  "dashboard.models.starterTemplateHint": "在接入模板库中使用此模型：",
  "dashboard.models.starterTemplateImage": "gpt-image-2 → Image 起步模板",
  "dashboard.models.startFromModelAutoCheap": "auto-cheap — 电商大批量文案",
  "dashboard.models.startFromModelAutoFast": "auto-fast — 首次测试",
  "dashboard.models.startFromModelAutoPro": "auto-pro — 高质量任务",
  "dashboard.models.startFromModelTitle": "从此模型开始接入",
  "dashboard.models.statusAvailable": "可用",
  "dashboard.models.statusComingSoon": "即将上线",
  "dashboard.models.statusPaused": "暂停",
  "dashboard.models.subtitle": "查看 Tokfai 当前可用模型、能力、推荐场景和计费说明。",
  "dashboard.models.tableDesc": "用于 API 请求与 Playground 的 model ID。",
  "dashboard.models.tableTitle": "模型列表",
  "dashboard.models.title": "模型",
  "dashboard.models.usageTipsTitle": "使用建议",
  "dashboard.models.verificationUnavailableNote": "若实时验证暂时不可用，可先选定模型方案，稍后在接入工作台完成验证。",
  "dashboard.models.viewCreditsLedger": "查看积分账本",
  "dashboard.overview.continueDesc": "继续测试、查看用量，或核对余额。",
  "dashboard.overview.continueTitle": "继续使用",
  "dashboard.overview.manageApiKeys": "管理 API Keys",
  "dashboard.overview.onboardingAllComplete": "接入已完成，可以开始正式集成。",
  "dashboard.overview.recentActivityDesc": "最近五条 API 请求记录。",
  "dashboard.overview.recentActivityEmpty": "暂无 API 调用。完成 Playground 测试后，最近请求会显示在这里。",
  "dashboard.overview.recentActivityTitle": "最近活动",
  "dashboard.overview.recentActivityViewCredits": "查看 Credits",
  "dashboard.overview.recentActivityViewUsage": "查看 Usage",
  "dashboard.overview.securityTitle": "安全提醒",
  "dashboard.overview.stateNeedsFirstCallPlayground": "Chat Playground",
  "dashboard.overview.stateNeedsFirstCallQuickstart": "查看 Quick Start",
  "dashboard.overview.stepCompleted": "已完成",
  "dashboard.overview.stepCurrent": "当前步骤",
  "dashboard.overview.stepNext": "待完成",
  "dashboard.overview.title": "Overview",
  "dashboard.overview.viewAllUsage": "查看全部用量",
  "dashboard.playground.apiKey": "API Key",
  "dashboard.playground.apiKeyLoadTimedOut": "加载所选 API Key 超时。请粘贴完整 secret 或稍后重试。",
  "dashboard.playground.copied": "已复制",
  "dashboard.playground.copyRequestId": "复制 request_id",
  "dashboard.playground.copySecret": "复制 secret",
  "dashboard.playground.costHint": "Playground 会消耗 credits，请先确认余额。实际扣费以积分账本为准。",
  "dashboard.playground.createdAt": "created_at",
  "dashboard.playground.createTestKey": "创建测试 Key",
  "dashboard.playground.creatingTestKey": "创建中…",
  "dashboard.playground.creditsCharged": "credits charged",
  "dashboard.playground.currentKeySelection": "当前选择：{name}（{prefix}…）",
  "dashboard.playground.errors.invalidToken": "API Key 无效或已吊销，请重新创建。",
  "dashboard.playground.errors.keyNotRetrievable": "出于安全考虑，完整 key 不会长期保存。请粘贴 key，或重新创建一个测试 Key。",
  "dashboard.playground.errors.missingPrompt": "请输入测试内容。",
  "dashboard.playground.errors.missingToken": "缺少 API Key，请先创建并选择可用密钥。",
  "dashboard.playground.errors.unknown": "请求失败，请稍后重试。",
  "dashboard.playground.errors.upstreamError": "当前模型暂时不可用或负载较高。",
  "dashboard.playground.forImageModels": "图像模型请使用",
  "dashboard.playground.fullApiKey": "完整 API Key",
  "dashboard.playground.goToApiKeys": "前往 API Keys",
  "dashboard.playground.hideKey": "隐藏",
  "dashboard.playground.inputTokens": "input tokens",
  "dashboard.playground.manageApiKeys": "管理 API Keys",
  "dashboard.playground.manageApiKeysHint": "如需吊销或删除密钥，请前往 API Keys 页面管理。",
  "dashboard.playground.model": "模型",
  "dashboard.playground.noKeyBody": "创建一个测试 Key 后，即可在 Playground 里完成第一次真实调用。",
  "dashboard.playground.noKeyTitle": "还没有可用 API Key",
  "dashboard.playground.outputTokens": "output tokens",
  "dashboard.playground.pasteKey": "粘贴密钥",
  "dashboard.playground.pasteKeySecurityHint": "密钥仅保存在当前页面 state，不会写入数据库。请勿在公共设备保存密钥。",
  "dashboard.playground.pasteOtherKey": "粘贴其他 Key",
  "dashboard.playground.productionKeyHint": "用于生产接入时，请在 API Keys 页面创建并复制 sk-tokfai 密钥。",
  "dashboard.playground.prompt": "Prompt",
  "dashboard.playground.promptPlaceholder": "请输入测试内容，例如：用一句话介绍 Tokfai API。",
  "dashboard.playground.request": "测试请求",
  "dashboard.playground.requestDesc": "选择或创建 API Key，选择对话模型，发送一条非流式消息进行测试。",
  "dashboard.playground.requestedModel": "请求 model",
  "dashboard.playground.requestId": "request_id",
  "dashboard.playground.requestStatus": "请求状态",
  "dashboard.playground.resolvedModel": "实际 model",
  "dashboard.playground.responseContent": "回复内容",
  "dashboard.playground.responsePlaceholder": "发送测试后，模型回复将显示在这里。",
  "dashboard.playground.resultTitle": "结果",
  "dashboard.playground.run": "发送测试",
  "dashboard.playground.running": "发送中…",
  "dashboard.playground.secretNotStored": "完整 secret 仅用于本次请求，不会保存在浏览器中。",
  "dashboard.playground.secretOnceHint": "完整 secret 只在创建时展示一次。刷新页面后将无法再次查看，如遗失请重新创建。",
  "dashboard.playground.selectKey": "选择密钥",
  "dashboard.playground.showKey": "显示",
  "dashboard.playground.statusFailed": "失败",
  "dashboard.playground.statusSuccess": "成功",
  "dashboard.playground.subtitle": "选择模型，发送一次测试请求，验证 Tokfai API 是否正常工作。",
  "dashboard.playground.successBalanceHint": "已记录至",
  "dashboard.playground.successReconcileHint": "复制 request_id，在 Usage 与 Credits 中搜索以核对本次调用。",
  "dashboard.playground.testKeyCreated": "测试 Key 已创建。请复制完整 secret；刷新页面后不会再次显示。",
  "dashboard.playground.testNow": "立即测试",
  "dashboard.playground.title": "Playground",
  "dashboard.playground.tokensNotReturned": "—",
  "dashboard.playground.totalTokens": "total tokens",
  "dashboard.playground.usageFallback": "本次消耗请以 /dashboard/credits 积分账本为准。",
  "dashboard.playground.viewChatApiDocs": "Chat API 文档",
  "dashboard.playground.viewCredits": "查看 Credits",
  "dashboard.playground.viewCreditsLedger": "查看积分账本",
  "dashboard.playground.viewDocs": "查看文档",
  "dashboard.playground.viewModels": "查看模型",
  "dashboard.playground.viewOpenAiSdkDocs": "OpenAI SDK 文档",
  "dashboard.playground.viewUsage": "查看 Usage",
  "dashboard.playground.waitingForModel": "等待模型响应…",
  "dashboard.shell.lowCredits": "积分较低",
  "dashboard.shell.productTagline": "OpenAI 兼容 API 网关",
  "dashboard.shell.sidebarCreditsLabel": "积分余额",
  "dashboard.shell.topUp": "充值",
  "dashboard.usage.colCompletion": "Completion",
  "dashboard.usage.colCredits": "扣除积分",
  "dashboard.usage.colModel": "Model",
  "dashboard.usage.colPrompt": "Prompt",
  "dashboard.usage.colRequestId": "请求 ID",
  "dashboard.usage.colRequestIdHint": "联系支持排查问题时提供",
  "dashboard.usage.colRoute": "Route",
  "dashboard.usage.colStatus": "状态",
  "dashboard.usage.colTotal": "Total",
  "dashboard.usage.colWhen": "时间",
  "dashboard.usage.copiedRequestId": "已复制",
  "dashboard.usage.copyRequestId": "复制 request_id",
  "dashboard.usage.emptyHint": "在 Chat Playground 或 Image Playground 发送测试请求，成功调用后会出现在这里。",
  "dashboard.usage.emptyTitle": "暂无用量记录。",
  "dashboard.usage.emptyViewCredits": "查看积分账本",
  "dashboard.usage.howItWorksItem1": "每一行对应一次 API 请求，包含 model、route、状态、tokens、credits_charged 与 request_id。",
  "dashboard.usage.howItWorksItem2": "对话行展示 prompt / completion / total tokens；图像行展示每次生成的 credits。",
  "dashboard.usage.howItWorksItem3": "Credits 页余额与本页记录一致——Usage 与 Credits 是核账来源。",
  "dashboard.usage.howItWorksItem4": "失败请求会显示在此，但不扣费。",
  "dashboard.usage.howItWorksItem5": "失败请求用于排查，一般不扣 credits；成功请求会记录 tokens 与 credits_charged。",
  "dashboard.usage.howItWorksTitle": "如何阅读本页",
  "dashboard.usage.imageGeneration": "image generation",
  "dashboard.usage.integrationWorkbenchLink": "接入工作台 — 对账 request_id",
  "dashboard.usage.loadError": "无法加载用量",
  "dashboard.usage.loadErrorDesc": "暂时无法加载用量记录，请稍后重试。",
  "dashboard.usage.loadingRecentRequests": "最近请求",
  "dashboard.usage.loadingRecentRequestsDesc": "正在加载最新用量记录…",
  "dashboard.usage.recentRequests": "最近请求",
  "dashboard.usage.recentRequestsDesc": "最近 50 条，按时间倒序。在 Chat Playground 或 Image Playground 发起请求以产生更多记录。",
  "dashboard.usage.statCredits7d": "最近 7 天 credits 消耗",
  "dashboard.usage.statRequests24h": "最近 24 小时请求数",
  "dashboard.usage.statRequests7d": "最近 7 天请求数",
  "dashboard.usage.statTokens7d": "最近 7 天 tokens",
  "dashboard.usage.subtitle": "查看 API 请求、model、状态、token 用量与 credits 消耗。",
  "dashboard.usage.title": "用量",
  "integration.apiKeyBulletAuthHeader": "请求头格式固定为 Authorization: Bearer sk-tokfai_xxx（xxx 替换为你的 secret）。",
  "integration.apiKeyBulletOneKeyAllApis": "一把 API Key 可用于 Chat API、Image API、Batch API——无需为每个模型单独创建密钥。",
  "integration.apiKeyBulletOneTime": "完整 secret 仅在创建密钥时展示一次——请立即复制保存。",
  "integration.apiKeyBulletReveal": "活跃密钥可在 API Keys 页面通过「复制密钥」（reveal）再次获取完整 secret。",
  "integration.apiKeyBulletRevoke": "密钥泄露后请立即 Revoke，并创建新密钥。",
  "integration.apiKeyBulletServerSide": "密钥只应放在服务端、脚本、IDE 或网关配置中——不要写入公开前端或公开源码。",
  "integration.apiKeyCopyNowTitle": "你现在就可以复制",
  "integration.apiReadiness.apiKeysHint": "若实时验证不可用，请妥善保存此密钥，并继续在接入工作台完成准备。",
  "integration.linkCredits": "打开 Credits",
  "integration.nav500OnlineReadiness": "500 人在线准备",
  "integration.navCapacityPlanner": "容量规划器",
  "integration.navRetryBackoff": "重试与退避",
  "integration.navTrafficGovernor": "流量治理",
  "integration.oneLineCurlPasteAnywhere": "复制后粘贴到任意终端即可。不需要安装，不需要进入项目目录。",
  "integration.starterTemplates.openLibrary": "打开接入模板库",
  "integration.trafficGovernor.scaleSafelyTitle": "安全扩容",
  "integration.troubleshooting.curlFailsTitle": "若 curl 失败",
  "integration.troubleshooting.invalidTokenGuide": "invalid_token 指南",
  "integration.troubleshooting.missingTokenGuide": "missing_token 指南",
  "integration.troubleshooting.openTroubleshooting": "打开故障排查",
  "nav.dashboard": "控制台",
  "quickstart.copied": "已复制",
  "quickstart.copy": "复制",
};
