import { TOKFAI_API_BASE_URL, TOKFAI_API_KEY_PLACEHOLDER } from "@/lib/tokfai-api";
import {
  BATCH_MAX_POLL_ATTEMPTS,
  BATCH_POLL_INTERVAL_SECONDS,
  DEFAULT_MAX_ATTEMPTS,
  NON_RETRYABLE_ERROR_CODES,
  RETRYABLE_ERROR_CODES,
} from "@/lib/customer-retry-policy";
import {
  DEFAULT_CHAT_MAX_CONCURRENT,
  DEFAULT_IMAGE_MAX_CONCURRENT,
} from "@/lib/customer-traffic-governor-policy";

const CHAT_MODEL = "auto-fast";
const IMAGE_MODEL = "gpt-image-2";
const CHAT_PROMPT = "Say ok only.";
const IMAGE_PROMPT = "A simple product photo on white background.";

const RETRYABLE_JS = RETRYABLE_ERROR_CODES.map((c) => `"${c}"`).join(", ");
const NON_RETRYABLE_JS = NON_RETRYABLE_ERROR_CODES.map((c) => `"${c}"`).join(", ");
const RETRYABLE_PY = RETRYABLE_ERROR_CODES.map((c) => `"${c}"`).join(", ");
const NON_RETRYABLE_PY = NON_RETRYABLE_ERROR_CODES.map((c) => `"${c}"`).join(", ");

/** Node.js traffic governor — queue + maxConcurrent + safe retry (Chat) */
export function buildNodeTrafficGovernor(apiKey = TOKFAI_API_KEY_PLACEHOLDER): string {
  const lines = [
    "// Save as tokfai-worker.mjs — run: node tokfai-worker.mjs (any folder)",
    `const API_KEY = process.env.TOKFAI_API_KEY ?? "${apiKey}";`,
    `const CHAT_URL = "${TOKFAI_API_BASE_URL}/chat/completions";`,
    `const MAX_CONCURRENT = ${DEFAULT_CHAT_MAX_CONCURRENT};`,
    `const MAX_ATTEMPTS = ${DEFAULT_MAX_ATTEMPTS};`,
    "const DELAYS_MS = [5000, 15000, 30000];",
    `const RETRYABLE = new Set([${RETRYABLE_JS}]);`,
    `const NON_RETRYABLE = new Set([${NON_RETRYABLE_JS}]);`,
    "",
    "function sleep(ms) {",
    "  return new Promise((r) => setTimeout(r, ms));",
    "}",
    "",
    "function isRetryable(status, body) {",
    "  if (status === 401 || status === 402 || status === 400 || status === 413) return false;",
    "  const code = body?.error?.code;",
    "  if (code && NON_RETRYABLE.has(code)) return false;",
    "  if (status === 429 || status === 503 || status === 504) return true;",
    "  if (status >= 500 && status < 600) return code ? RETRYABLE.has(code) : true;",
    "  return false;",
    "}",
    "",
    "async function callChat(content) {",
    "  const payload = {",
    `    model: "${CHAT_MODEL}",`,
    "    messages: [{ role: \"user\", content }],",
    "    stream: false,",
    "  };",
    "  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {",
    "    const res = await fetch(CHAT_URL, {",
    "      method: \"POST\",",
    "      headers: {",
    "        Authorization: `Bearer ${API_KEY}`,",
    "        \"Content-Type\": \"application/json\",",
    "      },",
    "      body: JSON.stringify(payload),",
    "    });",
    "    const body = await res.json();",
    "    if (res.ok) {",
    "      const tokfai = body.tokfai ?? {};",
    "      console.log(\"request_id:\", body.request_id ?? tokfai.request_id);",
    "      console.log(\"credits_charged:\", body.credits_charged ?? tokfai.credits_charged);",
    "      console.log(\"resolved_model:\", tokfai.resolved_model ?? body.model);",
    "      return body;",
    "    }",
    "    if (!isRetryable(res.status, body) || attempt === MAX_ATTEMPTS - 1) {",
    "      throw new Error(`${body.error?.code ?? res.status}: ${body.error?.message ?? \"failed\"}`);",
    "    }",
    "    const delay = DELAYS_MS[Math.min(attempt, DELAYS_MS.length - 1)] + Math.random() * 3000;",
    "    console.warn(`retry ${body.error?.code} — wait ${Math.round(delay)}ms`);",
    "    await sleep(delay);",
    "  }",
    "}",
    "",
    "class TrafficGovernor {",
    "  constructor(maxConcurrent) {",
    "    this.max = maxConcurrent;",
    "    this.active = 0;",
    "    this.queue = [];",
    "  }",
    "  run(task) {",
    "    return new Promise((resolve, reject) => {",
    "      this.queue.push({ task, resolve, reject });",
    "      this.pump();",
    "    });",
    "  }",
    "  pump() {",
    "    while (this.active < this.max && this.queue.length) {",
    "      const { task, resolve, reject } = this.queue.shift();",
    "      this.active++;",
    "      task()",
    "        .then(resolve)",
    "        .catch(reject)",
    "        .finally(() => {",
    "          this.active--;",
    "          this.pump();",
    "        });",
    "    }",
    "  }",
    "}",
    "",
    "const governor = new TrafficGovernor(MAX_CONCURRENT);",
    "const prompts = [\"Say ok.\", \"Say hi.\", \"Say hey.\"];",
    "await Promise.all(",
    "  prompts.map((content) => governor.run(() => callChat(content)))",
    ");",
    "console.log(\"done\", prompts.length, \"jobs\");",
  ];
  return lines.join("\n");
}

/** Node.js image traffic governor — low concurrency, conservative retry */
export function buildNodeImageGovernor(apiKey = TOKFAI_API_KEY_PLACEHOLDER): string {
  const lines = [
    "// Save as tokfai-image-worker.mjs — run: node tokfai-image-worker.mjs (any folder)",
    `const API_KEY = process.env.TOKFAI_API_KEY ?? "${apiKey}";`,
    `const IMAGE_URL = "${TOKFAI_API_BASE_URL}/images/generations";`,
    `const MAX_CONCURRENT = ${DEFAULT_IMAGE_MAX_CONCURRENT};`,
    `const MAX_ATTEMPTS = ${DEFAULT_MAX_ATTEMPTS};`,
    "const DELAYS_MS = [5000, 15000, 30000];",
    `const RETRYABLE = new Set([${RETRYABLE_JS}]);`,
    `const NON_RETRYABLE = new Set([${NON_RETRYABLE_JS}]);`,
    "",
    "function sleep(ms) {",
    "  return new Promise((r) => setTimeout(r, ms));",
    "}",
    "",
    "function isRetryable(status, body) {",
    "  if (status === 401 || status === 402 || status === 400 || status === 413) return false;",
    "  const code = body?.error?.code;",
    "  if (code && NON_RETRYABLE.has(code)) return false;",
    "  if (status === 429 || status === 503 || status === 504) return true;",
    "  if (status >= 500 && status < 600) return code ? RETRYABLE.has(code) : true;",
    "  return false;",
    "}",
    "",
    "async function callImage(prompt) {",
    "  const payload = {",
    `    model: "${IMAGE_MODEL}",`,
    "    prompt,",
    "    response_format: \"url\",",
    "    n: 1,",
    "  };",
    "  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {",
    "    const res = await fetch(IMAGE_URL, {",
    "      method: \"POST\",",
    "      headers: {",
    "        Authorization: `Bearer ${API_KEY}`,",
    "        \"Content-Type\": \"application/json\",",
    "      },",
    "      body: JSON.stringify(payload),",
    "    });",
    "    const body = await res.json();",
    "    if (res.ok) {",
    "      const tokfai = body.tokfai ?? {};",
    "      console.log(\"request_id:\", body.request_id ?? tokfai.request_id);",
    "      console.log(\"credits_charged:\", body.credits_charged ?? tokfai.credits_charged);",
    "      console.log(\"resolved_model:\", tokfai.resolved_model ?? body.model);",
    "      console.log(\"url:\", body.data?.[0]?.url);",
    "      return body;",
    "    }",
    "    if (!isRetryable(res.status, body) || attempt === MAX_ATTEMPTS - 1) {",
    "      throw new Error(`${body.error?.code ?? res.status}: ${body.error?.message ?? \"failed\"}`);",
    "    }",
    "    const delay = DELAYS_MS[Math.min(attempt, DELAYS_MS.length - 1)] + Math.random() * 3000;",
    "    console.warn(`retry ${body.error?.code} — wait ${Math.round(delay)}ms (low concurrency only)`);",
    "    await sleep(delay);",
    "  }",
    "}",
    "",
    "class TrafficGovernor {",
    "  constructor(maxConcurrent) {",
    "    this.max = maxConcurrent;",
    "    this.active = 0;",
    "    this.queue = [];",
    "  }",
    "  run(task) {",
    "    return new Promise((resolve, reject) => {",
    "      this.queue.push({ task, resolve, reject });",
    "      this.pump();",
    "    });",
    "  }",
    "  pump() {",
    "    while (this.active < this.max && this.queue.length) {",
    "      const { task, resolve, reject } = this.queue.shift();",
    "      this.active++;",
    "      task()",
    "        .then(resolve)",
    "        .catch(reject)",
    "        .finally(() => {",
    "          this.active--;",
    "          this.pump();",
    "        });",
    "    }",
    "  }",
    "}",
    "",
    "const governor = new TrafficGovernor(MAX_CONCURRENT);",
    `const prompts = ["${IMAGE_PROMPT}", "Minimal icon on white.", "Simple banner layout."];`,
    "await Promise.all(",
    "  prompts.map((prompt) => governor.run(() => callImage(prompt)))",
    ");",
    "console.log(\"done\", prompts.length, \"image jobs\");",
  ];
  return lines.join("\n");
}

/** Node.js batch worker — create, poll, items, summary */
export function buildNodeBatchWorker(apiKey = TOKFAI_API_KEY_PLACEHOLDER): string {
  const lines = [
    "// Save as tokfai-batch-worker.mjs — run: node tokfai-batch-worker.mjs (any folder)",
    `const API_KEY = process.env.TOKFAI_API_KEY ?? "${apiKey}";`,
    `const BASE = "${TOKFAI_API_BASE_URL}";`,
    `const POLL_INTERVAL_MS = ${BATCH_POLL_INTERVAL_SECONDS * 1000};`,
    `const MAX_POLLS = ${BATCH_MAX_POLL_ATTEMPTS};`,
    "",
    "const createRes = await fetch(`${BASE}/batches/chat`, {",
    "  method: \"POST\",",
    "  headers: {",
    "    Authorization: `Bearer ${API_KEY}`,",
    "    \"Content-Type\": \"application/json\",",
    "  },",
    "  body: JSON.stringify({",
    `    model: "${CHAT_MODEL}",`,
    "    items: [",
    `      { messages: [{ role: \"user\", content: \"${CHAT_PROMPT}\" }] },`,
    "      { messages: [{ role: \"user\", content: \"Summarize in one line.\" }] },",
    "    ],",
    "  }),",
    "});",
    "const created = await createRes.json();",
    "if (!createRes.ok) {",
    "  console.error(created.error?.code, created.error?.message);",
    "  process.exit(1);",
    "}",
    "const batchId = created.id;",
    "console.log(\"batch_id:\", batchId, \"request_id:\", created.request_id);",
    "",
    "let status = created.status;",
    "for (let i = 0; i < MAX_POLLS; i++) {",
    "  if (",
    "    status === \"completed\" ||",
    "    status === \"partial_failed\" ||",
    "    status === \"failed\" ||",
    "    status === \"cancelled\"",
    "  ) {",
    "    break;",
    "  }",
    "  await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));",
    "  const pollRes = await fetch(`${BASE}/batches/${batchId}`, {",
    "    headers: { Authorization: `Bearer ${API_KEY}` },",
    "  });",
    "  const poll = await pollRes.json();",
    "  status = poll.status;",
    "  console.log(\"poll\", i + 1, status, \"succeeded:\", poll.succeeded_items, \"failed:\", poll.failed_items);",
    "}",
    "",
    "if (status === \"cancelled\") {",
    "  console.error(\"batch_cancelled — do not retry\");",
    "  process.exit(1);",
    "}",
    "",
    "const itemsRes = await fetch(`${BASE}/batches/${batchId}/items`, {",
    "  headers: { Authorization: `Bearer ${API_KEY}` },",
    "});",
    "const itemsPayload = await itemsRes.json();",
    "let succeeded = 0;",
    "let failed = 0;",
    "let creditsCharged = 0;",
    "for (const item of itemsPayload.data ?? []) {",
    "  console.log(\"item\", item.index, item.status, \"request_id:\", item.request_id, \"credits:\", item.credits_charged);",
    "  if (item.status === \"succeeded\") succeeded++;",
    "  else if (item.status === \"failed\") failed++;",
    "  creditsCharged += item.credits_charged ?? 0;",
    "}",
    "console.log(\"summary:\", { status, succeeded, failed, credits_charged: creditsCharged });",
  ];
  return lines.join("\n");
}

/** Python traffic governor — ThreadPoolExecutor + requests */
export function buildPythonTrafficGovernor(apiKey = TOKFAI_API_KEY_PLACEHOLDER): string {
  const lines = [
    "# Save as tokfai_worker.py — run: python tokfai_worker.py (any folder)",
    "import os",
    "import random",
    "import time",
    "from concurrent.futures import ThreadPoolExecutor, as_completed",
    "",
    "import requests",
    "",
    `API_KEY = os.environ.get("TOKFAI_API_KEY", "${apiKey}")`,
    `CHAT_URL = "${TOKFAI_API_BASE_URL}/chat/completions"`,
    `MAX_WORKERS = ${DEFAULT_CHAT_MAX_CONCURRENT}`,
    `MAX_ATTEMPTS = ${DEFAULT_MAX_ATTEMPTS}`,
    "DELAYS = [5, 15, 30]",
    `RETRYABLE = {${RETRYABLE_PY}}`,
    `NON_RETRYABLE = {${NON_RETRYABLE_PY}}`,
    "",
    "",
    "def is_retryable(status, body):",
    "    if status in (401, 402, 400, 413):",
    "        return False",
    "    code = (body.get(\"error\") or {}).get(\"code\")",
    "    if code and code in NON_RETRYABLE:",
    "        return False",
    "    if status in (429, 503, 504):",
    "        return True",
    "    if 500 <= status < 600:",
    "        return code in RETRYABLE if code else True",
    "    return False",
    "",
    "",
    "def call_chat(content):",
    "    payload = {",
    `        "model": "${CHAT_MODEL}",`,
    "        \"messages\": [{\"role\": \"user\", \"content\": content}],",
    "        \"stream\": False,",
    "    }",
    "    for attempt in range(MAX_ATTEMPTS):",
    "        res = requests.post(",
    "            CHAT_URL,",
    "            headers={\"Authorization\": f\"Bearer {API_KEY}\"},",
    "            json=payload,",
    "            timeout=120,",
    "        )",
    "        body = res.json()",
    "        if res.ok:",
    "            tokfai = body.get(\"tokfai\") or {}",
    "            print(\"request_id:\", body.get(\"request_id\") or tokfai.get(\"request_id\"))",
    "            print(\"credits_charged:\", body.get(\"credits_charged\") or tokfai.get(\"credits_charged\"))",
    "            print(\"resolved_model:\", tokfai.get(\"resolved_model\") or body.get(\"model\"))",
    "            return body",
    "        err = body.get(\"error\") or {}",
    "        if not is_retryable(res.status_code, body) or attempt == MAX_ATTEMPTS - 1:",
    "            raise RuntimeError(f\"{err.get('code')}: {err.get('message')}\")",
    "        delay = DELAYS[min(attempt, len(DELAYS) - 1)] + random.uniform(0, 3)",
    "        print(f\"retry {err.get('code')} — wait {delay:.1f}s\")",
    "        time.sleep(delay)",
    "",
    "",
    "prompts = [\"Say ok.\", \"Say hi.\", \"Say hey.\"]",
    "with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:",
    "    futures = [pool.submit(call_chat, p) for p in prompts]",
    "    for fut in as_completed(futures):",
    "        fut.result()",
    "print(\"done\", len(prompts), \"jobs\")",
  ];
  return lines.join("\n");
}

/** Python batch worker */
export function buildPythonBatchWorker(apiKey = TOKFAI_API_KEY_PLACEHOLDER): string {
  const lines = [
    "# Save as tokfai_batch_worker.py — run: python tokfai_batch_worker.py (any folder)",
    "import os",
    "import time",
    "",
    "import requests",
    "",
    `API_KEY = os.environ.get("TOKFAI_API_KEY", "${apiKey}")`,
    `BASE = "${TOKFAI_API_BASE_URL}"`,
    `POLL_INTERVAL = ${BATCH_POLL_INTERVAL_SECONDS}`,
    `MAX_POLLS = ${BATCH_MAX_POLL_ATTEMPTS}`,
    "",
    "create = requests.post(",
    "    f\"{BASE}/batches/chat\",",
    "    headers={\"Authorization\": f\"Bearer {API_KEY}\"},",
    "    json={",
    `        "model": "${CHAT_MODEL}",`,
    "        \"items\": [",
    `            {"messages": [{"role": "user", "content": "${CHAT_PROMPT}"}]},`,
    "            {\"messages\": [{\"role\": \"user\", \"content\": \"Summarize in one line.\"}]},",
    "        ],",
    "    },",
    "    timeout=120,",
    ")",
    "created = create.json()",
    "if not create.ok:",
    "    print(created.get(\"error\", {}).get(\"code\"), created.get(\"error\", {}).get(\"message\"))",
    "    raise SystemExit(1)",
    "",
    "batch_id = created[\"id\"]",
    "print(\"batch_id:\", batch_id, \"request_id:\", created.get(\"request_id\"))",
    "",
    "status = created.get(\"status\")",
    "for i in range(MAX_POLLS):",
    "    if status in (\"completed\", \"partial_failed\", \"failed\", \"cancelled\"):",
    "        break",
    "    time.sleep(POLL_INTERVAL)",
    "    poll = requests.get(",
    "        f\"{BASE}/batches/{batch_id}\",",
    "        headers={\"Authorization\": f\"Bearer {API_KEY}\"},",
    "        timeout=60,",
    "    )",
    "    body = poll.json()",
    "    status = body.get(\"status\")",
    "    print(\"poll\", i + 1, status, \"succeeded:\", body.get(\"succeeded_items\"), \"failed:\", body.get(\"failed_items\"))",
    "",
    "if status == \"cancelled\":",
    "    print(\"batch_cancelled — do not retry\")",
    "    raise SystemExit(1)",
    "",
    "items_res = requests.get(",
    "    f\"{BASE}/batches/{batch_id}/items\",",
    "    headers={\"Authorization\": f\"Bearer {API_KEY}\"},",
    "    timeout=60,",
    ")",
    "items_payload = items_res.json()",
    "succeeded = 0",
    "failed = 0",
    "credits_charged = 0",
    "for item in items_payload.get(\"data\") or []:",
    "    print(",
    "        \"item\",",
    "        item.get(\"index\"),",
    "        item.get(\"status\"),",
    "        \"request_id:\",",
    "        item.get(\"request_id\"),",
    "        \"credits:\",",
    "        item.get(\"credits_charged\"),",
    "    )",
    "    if item.get(\"status\") == \"succeeded\":",
    "        succeeded += 1",
    "    elif item.get(\"status\") == \"failed\":",
    "        failed += 1",
    "    credits_charged += item.get(\"credits_charged\") or 0",
    "print(\"summary:\", {\"status\": status, \"succeeded\": succeeded, \"failed\": failed, \"credits_charged\": credits_charged})",
  ];
  return lines.join("\n");
}

/** Browser frontend API key safety — copy as checklist */
export function buildBrowserKeyCautionSnippet(): string {
  return [
    "Browser frontend API key safety (Tokfai customer guide)",
    "",
    "1. Do NOT embed sk-tokfai_* keys in public web pages, mobile apps, or browser extensions.",
    "2. Route Tokfai calls through your own backend server that holds the API Key.",
    "3. Your backend applies queue, concurrency limits, and safe retry — not the browser.",
    "4. Tokfai provides API access; you operate your application stack.",
    "5. Reconcile request_id in Usage / Credits from your server logs.",
    "",
    "For one-line verification curl, copy from Dashboard → API Keys (paste in Terminal).",
  ].join("\n");
}

export const TRAFFIC_GOVERNOR_SNIPPET_IDS = [
  "node-traffic-governor",
  "node-image-governor",
  "node-batch-worker",
  "python-traffic-governor",
  "python-batch-worker",
  "browser-key-caution",
] as const;

export type TrafficGovernorSnippetId = (typeof TRAFFIC_GOVERNOR_SNIPPET_IDS)[number];

export function buildTrafficGovernorSnippet(
  id: TrafficGovernorSnippetId,
  apiKey = TOKFAI_API_KEY_PLACEHOLDER
): string {
  switch (id) {
    case "node-traffic-governor":
      return buildNodeTrafficGovernor(apiKey);
    case "node-image-governor":
      return buildNodeImageGovernor(apiKey);
    case "node-batch-worker":
      return buildNodeBatchWorker(apiKey);
    case "python-traffic-governor":
      return buildPythonTrafficGovernor(apiKey);
    case "python-batch-worker":
      return buildPythonBatchWorker(apiKey);
    case "browser-key-caution":
      return buildBrowserKeyCautionSnippet();
  }
}
